### ISSUE TITLE
Option to indent PHP code based on the HTML around it

### ISSUE THREAD

**Issue by davion100** [adobe/brackets#10038]
Hello. I have a problem with the PHP code not indenting properly. What happens is every time I type "<?php" all the code after this line does not indent. I tried removing all the plugins , same thing. Here is an example: 
![mxx2yqi](https://cloud.githubusercontent.com/assets/6960329/5226342/7c2f80b2-76f6-11e4-9e05-695e73122249.png)

**Comment by rifton007** [comment]
Hi all,
I have the same problem, the news about it?

**Comment by juliancesar** [comment]
I have the same problem! Any news?

**Comment by klarkc** [comment]
+1

**Comment by MarcelGerber** [comment]
Just submitted the CodeMirror tracking issue https://github.com/codemirror/CodeMirror/issues/3488

**Comment by MarcelGerber** [comment]
This will work as described beginning in Release 1.5.
Closing.

**Comment by vidukapoor** [comment]
php code writing error.

**Comment by mikael1000** [comment]
I have 1.5... and it don't work. This should be fixed!
However you get a little better experience if you do the hack with { and }:
<?php {
}?>

But that's a bad way to have to do this.

**Comment by ficristo** [comment]
@mikael1000 Brackets align the code at the same level of `<?php`: so it's indented.
In general I think it should indent one more time but I don't know enough of `php` to say it's the right thing to do.
Since I can reproduce the "issue" on the [demo page](http://codemirror.net/mode/php/) of CodeMirror you should file a bug there.
