### ISSUE TITLE
Highlight 'text/ng-template' (Angular) in script tags as HTML, not plain text

### ISSUE THREAD

**Issue by amambrini** [adobe/brackets#10166]
Brackets does not highlight syntax for code inside <script> </script> tags.

That is not convenient when, for example, a tab-based interface is build using AngularUI Router since the code for each tab would be inside <script></script> tags. See for example the following implementation using ionic framework http://ionicframework.com/docs/api/directive/ionNavView/  the code in the third box would not get syntax highlight.

Is there any configuration or extension to fix this?

**Comment by peterflynn** [comment]
Marking as a starter bug since the fix for this specific case should be easy (and changed to a more specific title).

The [Language Extensibility epic card](https://trello.com/c/D2L7SAq5/639-epic-language-extensibility-apis-for-extensions-to-add-new-language-syntax-coloring-mode-rich-editing-support) on our feature backlog tracks the idea of making nested languages extensible in a more general sense.  (Though extensions could use CodeMirror overlay modes to hack in support for nested languages now, it could be done more cleanly if we put some effort into it).

**Comment by enalposi** [comment]
Hi, sorry for the noise, but same problem exists for "text/x-kendo-template". Could we please have a more generic solution?

**Comment by darkcoderrises** [comment]
Hi, I would like to work on this. Can someone guide me?

**Comment by MarcelGerber** [comment]
This should already work as of Release 1.3 (#10666). Does it not work for you?

Closing for now. We'll reopen if there are any issues.

**Comment by ShinDarth** [comment]
Using Brackets 1.7:

![image](https://cloud.githubusercontent.com/assets/75517/16002501/3c76aae0-3158-11e6-91cd-cc3fd7c1b3e1.png)

**Comment by ficristo** [comment]
@ShinDarth Use `text/ng-template` instead of `text/template` for the type.
