### ISSUE TITLE
eliminate the right click delete

### ISSUE THREAD

**Issue by Lee4LH** [adobe/brackets#10190]
This is un-needed and creates risk

**Comment by pthiess** [comment]
Please refer to the discussion in the PR.

**Comment by peterflynn** [comment]
Closing since we don't intend to remove the menu item, and bug #8651 already tracks the addition of a confirmation dialog (see PR #10258 for work in progress).  You could probably hack together an extension that strips out the menu item though, if you _really_ want it gone.

@Lee4LH You also mentioned though that files are not going to the Trash / Recycle bin for you.  Are you working with files that are on a thumb drive or a network share?  Also, what OS are you on?  (@thany if you're seeing the same problem with files not going to Trash/Recycle, could you answer those questions too?).

**Comment by Denisov21** [comment]
:+1: for the recycle bin / trash
:+1: for a "are you sure" message when a recycle bin/trash isn't available.

**Comment by thany** [comment]
@peterflynn A file for me does go to the recycle bin. But on a volume that has no recycle bin (like a network folder, or removable drive, or simply a disk on which the recycler is disabled) a file is deleted instantly and permanently.

**Comment by MarcelGerber** [comment]
A Confirm dialog is now shown when deleting a file.
Closing.
