### ISSUE TITLE
Opening Mac OS X aliases in folder tree

### ISSUE THREAD

**Issue by MCBL** [adobe/brackets#10230]
It seems that Brackets tries to open Mac OS X aliases as files.

Would it be better to open the aliased folder and go into it?

It's what I was waiting for.

**Comment by peterflynn** [comment]
Adding 'needs review' since it's not entirely clear what the right behavior should be.  Do we want to treat it as a symlink and show its contents when expanded?  That could be bug-prone since the paths won't actually be prefixed with the path of the "parent folder" (which is not true of real symlinks).  What do other editors do (or other tools in general with a file tree browsing pane)?

**Comment by MCBL** [comment]
Brackets could ask to open the folder and make it the active folder.
Windows links are potentially concerned too, to test.

**Comment by prksingh** [comment]
@MCBL It seems like this could be a good idea for an extension. It could be implemented using custom viewers. If this is uncommon in other editors than an extension seems like the best approach.

**Comment by jSchez** [comment]
Hello !

This can be easilly done by making a symboling link through any shell.
Something like "ln -s source_directory destination_directory"

If, for example you'd have a "controllers" directory in your local web server but you are editing the "views" nowdays, u'd make a symbolink link like this:

ln -s /Applications/MAMP/htdocs/dummy/controllers /Applications/MAMP/htdocs/dummy/views/controllers_link

This way, you can manage controllers directory from views directory tree. 

You'd be carefull about renaming the source directory since you will loose your symbolink link.

Kind regards !
