### ISSUE TITLE
Suggested Plugin: Per-line comments

### ISSUE THREAD

**Issue by rolyataylor2** [adobe/brackets#10328]
What I am thinking is a right aligned, or floating comment field on each line. Instead of having to tab over to align the comments in the document.

So normally would type some code
```
$this->find('user=100');
```

Then i want to add a comment like this
```
$this->find('user=100');    // Find the user in the stack
```
I want to have the comment line up with the other comments in the document. What I am doing currently is
```
{{ linecode }}+tab+tab+tab+// comment
{{ linecode }}+tab+tab+// comment
```

But the inconstancy in number of tabs and the time it takes to tab over is frustrating. What would be nice is if I add a comment to the end of a line the IDE could automatically add in the tabs to align all the comments for the raw file and show the comment in a split pane view or above the line text when the line isn't selected.

**Comment by peterflynn** [comment]
You may want to try the "Align It!" extension, or post a feature request specifically in that extension's repo if it seems like a good fit for this functionality.

I'll tag this 'extension idea' and close it, since that's out standard process for extension suggestions that we're not likely to turn into core features (we have a bunch of links pointing extension authors to search queries for the 'extension idea' label, and those queries include issues that have been closed).

**Comment by PhiLhoSoft** [comment]
See also http://nickgravgaard.com/elastic-tabstops/ :-)
