### ISSUE TITLE
Rails/HAML support for Live Preview

### ISSUE THREAD

**Issue by matthewbivins** [adobe/brackets#10340]
I love the functionality and concept of Live Preview, but it currently does not work with HAML, so I'm not sure that I can use it in a Rails project. This would be fantastic.

**Comment by peterflynn** [comment]
You can use Live Preview with your own server and still get live CSS updating & highlighting.  You just won't get live HTML updating.  Instructions here: [Live Preview - Using your own backend](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#lp-custom-server).

Editing server-side HAML pages with real-time Live Preview updating is complex since HAML is a templating language that can reference server-side state that Brackets doesn't have access to. See [Live HTML updating with user web server (Node, Rails, etc.) & static HTML on Brackets](https://trello.com/c/U9iOhk4J/1129-live-html-updating-with-user-web-server-node-rails-etc-static-html) followed by [Live Development: Live Highlight HTML Elements in Templates](https://trello.com/c/AbPpKAX0/689-live-development-live-highlight-html-elements-in-templates).  Since those items are already tracked on our feature backlog, I'll close this bug to avoid duplication.  Please upvote the backlog items to help raise their priority.
