### ISSUE TITLE
External changes conflict dialog is confusing/unclear

### ISSUE THREAD

**Issue by Squ34k3rZ** [adobe/brackets#10341]
Get this screen, wonder what it means. Scared to push either button because it means losing my work somehow. Needs to be more clear please.

![screen shot 2015-01-09 at 12 56 14 pm](https://cloud.githubusercontent.com/assets/4743518/5685350/0b363ac0-97ff-11e4-8034-1db116a667d8.png)

**Comment by Squ34k3rZ** [comment]
Are the changes in editor the changes I made? Did I make those changes in the editor or did I make those change to the files externally and now I have to decide if I keep changes in editor? This needs to be more clear please because it freaks me out on a weekly basis.

**Comment by le717** [comment]
If you read the dialog carefully, you'll see it is clear in what it says.

You have edited the file but have not yet saved your changes. However, Brackets has detected that the file has been edited in some form (could be as simple as an open and close) by an _external_ process, AKA not Brackets. Because it is impossible to tell what changed, and we don't want to cause you to loose your work, this box comes up asking if you want to keep the unsaved changes you've made in Brackets or use the possible changes performed by an outside process. Because, as I said, it's impossible to discover the external differences, it is up to you to decide what to do.

Does that make sense now?

**Comment by peterflynn** [comment]
It does say "External Change" in huge font at the top of the dialog already, but I suppose we could tweak the message body to make it more explicit, e.g.:

"\<file> has been modified on disk outside of Brackets, but also has unsaved changes in Brackets."
("outside of Brackets" is the new part)

@Squ34k3rZ Would that help?

But to answer this question more directly:
> Did I make those changes in the editor or did I make those change to the files externally and now I have to decide if I keep changes in editor?

The answer is "both" -- that's why you're seeing the message.  You have made changes in the editor _and_ the file has changed externally, creating a conflict between the two.  In most workflows, you would very rarely encounter this situation.

**Comment by Squ34k3rZ** [comment]
Thank you for your prompt response. My uncertainty is which label to choose to go with the file I changed externally. This happens when I want to git pull to another branch.

I don't know what Reload from Disk means. Does that mean I get the file with external changes?

I don't know what Keep Changes in Editor means either. What changes? The changes I made using the editor or the changes I just recently made to the file with git?

Thanks for your support!

**Comment by MarcelGerber** [comment]
Yeah, we could/should make that clearer, too.

You're right, "Reload from disk" updates the editor with the external changes, so you get the version you've just `git pull`ed. OTOH, "Keep Changes in Editor" keeps the editor content unchanged, it just keeps the changes you made in Brackets.

**Comment by rroshan1** [comment]
Verified the fix.. External changes conflict dialog is clearer!! 
Closing the issue.

**Comment by MrZolile** [comment]
Its a boring message. what is the solution for stopping the error message
