### ISSUE TITLE
Arduino

### ISSUE THREAD

**Issue by serhiyresera** [adobe/brackets#10391]
This would be an interesting thing to add the open source Arduino code, and maybe the compilator too :smile:

**Comment by sprintr** [comment]
Have a look at https://github.com/apla/brackets-cuwire

**Comment by peterflynn** [comment]
@serhiyresera Hardware programming is pretty far from Brackets's focus, even though I agree Arduino is cool!  The best solution is for someone to write a Brackets extension for this -- I'll add the 'extension idea' label so that people interested in creating an extension can see this idea.  I'll close the bug though, since we're unlikely to make this a core Brackets feature.

**Comment by serhiyresera** [comment]
Thank you very much!!

Inviato da iPhone
