### ISSUE TITLE
add interactive hinting/linting

### ISSUE THREAD

**Issue by intergalactic-overlords** [adobe/brackets#10414]
I would like to have hinting and linting while you type, with inline highlighting and comments.

Here is a plugin which has some of these features: https://github.com/MiguelCastillo/Brackets-InteractiveLinter

If it was build in to brackets, all hinting/linting libraries could make use of this system.

Prerequisites: live evaluation of files (now only happens when saving a file).

**Comment by MiguelCastillo** [comment]
@intergalactic-overlords There is already a trello card for this.  Out of curiosity, is there a particular why the extension isn't sufficient?

**Comment by peterflynn** [comment]
Closing since we already have this suggestion tracked on our feature backlog: ["Live" real-time linting as you type](https://trello.com/c/z1PBjZxt/588-live-real-time-linting-as-you-type).  @intergalactic-overlords: please upvote that to indicate your interest and help raise its priority.

@MiguelCastillo: I think it does make sense to have this capability built in eventually, so that all linting providers get the same benefit and Brackets is able to manage the performance characteristics more centrally.  That's why we have the card still open.

**Comment by MiguelCastillo** [comment]
@peterflynn Yeah it makes sense to have it in brackets. I was just wondering if there is particular functionality that the extension is lacking.

**Comment by intergalactic-overlords** [comment]
@MiguelCastillo, there is no (straightforward) way to make the extension work with other hinting/linting libraries. (otherwise, excellent extension ;-) )
