### ISSUE TITLE
Feature Request: CSV Support

### ISSUE THREAD

**Issue by mattmacadams** [adobe/brackets#10449]
Hi guys

I work with CSV files as the initial data input for my web apps.  Switching back and forth from "office" programs isn't much fun, and it doesn't seem too much of a stretch to better support these file types in Brackets..  It would be really nice if brackets would support either a table view for CSV files.  This would apply only when the user selects "CSV" as the file type.  If the user wants to view the raw text of the CSV file, they can simply choose "Text" as the file type.  A simply html table with resizable columns could do the trick, as long as the field remained editable.  

You can take this idea one step further and add support for Tab (TSV) and Pipe (PSV) file formats as well.

Let me know your thoughts.  I don't have any experience with brackets extensions or the underlying codebase, but happy to help contribute to this project in whatever way I can.

**Comment by peterflynn** [comment]
CSV files aren't that common in web development, so we probably wouldn't make this a core feature -- but it's a great idea for a Brackets extension.  It should be possible to do this by [registering a new language](https://github.com/adobe/brackets/wiki/Language-Support#defining-a-new-language) for the .csv file extension, and then [registering a custom viewer](https://github.com/adobe/brackets/blob/master/src/view/MainViewFactory.js#L30-L63) that responds to files of that type.  See the built-in Brackets feature for an [example of a custom viewer](https://github.com/adobe/brackets/blob/master/src/editor/ImageViewer.js).

Closing since extension ideas don't need to be left as open issues to show up in the right queries.
