### ISSUE TITLE
Find dialog should stay open, or remember value

### ISSUE THREAD

**Issue by cfjedimaster** [adobe/brackets#10455]
I was working within one file and needed to find instances of "lightroom". I needed to examine each result and decide if it needed editing. I did ctrl+f, typed in lightroom, and hit enter. I used the arrow to navigate forward until I found an instance I needed to modify. I typed in the editor and noticed that the file dialog automatically dismissed. When I hit ctrl+f again, my previous input was gone.

Shouldn't it persist so I can use my last search again?

**Comment by le717** [comment]
This is a super well known bug that is already [logged](https://trello.com/c/TD4qOgxG/1084-find-replace-leave-search-bar-open-highlights-visible-when-editor-focused-until-first-edit). I would like it to be fixed soon too.

In the mean time, once it goes away, just use F3 and Shift+F3 to find the next/previous result instead of hitting Ctrl+F again, which will clear all results.

**Comment by peterflynn** [comment]
See also [Find: Recent search history](https://trello.com/c/IzACddEv/344-find-recent-search-history), which would also improve this situation.

Closing since these are all fully captured on the feature backlog already -- please upvote the items there.
