### ISSUE TITLE
[L10N][JPN]: Sample project name "Getting Started" is not localized. 

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets#10478]
Steps:
1. Launch Brackets
2. Open the default sample project

Result:
The project name "Getting Started" is not localized.

Expected:
The string should be localized.

Notes:
This string is localized in French and it is not in ALF database. We had a discussion about this issue. From localization testing aspect, this string should be localized. Yoko commented that we normally avoid translating folder names in Asian script and suggested that we leave as is. File this issue to track and wait the final decision. 

ENV: MAC 10.9 and Win8 Japanese OS
Build: 1.2.0-15640

Screenshots:
![11](https://cloud.githubusercontent.com/assets/4251563/5954711/f3cc8592-a7d5-11e4-8cb5-54e248441896.png)

**Comment by peterflynn** [comment]
@julieyuan We currently can't use non-ANSI chars in these folder names due to limitations of Windows Installer.  Bug #2425 tracks that issue.  (This might also be why the French version doesn't have the right accents, but I'm not 100% sure).

Because it's so limited and the root string has never changed in the history of Brackets, trying to externalize the string somewhere ALF can see it seems like a low priority.

**Comment by peterflynn** [comment]
Also note: if we implemented [Getting Started outside of Application Root](https://trello.com/c/RybCpymr/632-getting-started-outside-of-application-root), it would make it much simpler to fix both the issues I mentioned above.  That enhancement is relatively low-priority right now too, though.

**Comment by rawat11** [comment]
closing the issue, as we avoid translating folder names in Asian script
