### ISSUE TITLE
non-utf8 files restriction

### ISSUE THREAD

**Issue by Azakur4** [adobe/brackets#10475]
Hi i write about this topic again to make a request to the team, is it possible to remove the restriction to open non utf8 files?

i know that by doing this u can confuse some users thinking they can edit all his files and in the end corrupt the files but maybe we can do this as an option to brackets, if u wanna turn on the restriction or if u wanna take it off.

I want this cuz this restriction stops a lot new ideas for extensions that can be work in solutions to this topic.

Currently atom editor have a solution that work in node.js, atom editor let u open a file without caring about the encoding (utf8 default enconding) but they let u an option in bottom to manually change the encoding that can be selected from a list. This made me think, i wrote an extension for brackets before, this extension read a file in any enconding and convert this to utf8 enconding creating a new file with the content.

Now, without this restriction we would be able to replace the content of the editor directly with the result of the conversion and we wouldn't have to create another file for this. With this we can get an initial solution to work with non-utf8 files.

**Comment by peterflynn** [comment]
Please upvote this item on our feature backlog to help raise its priority: [Support Encodings Other Than UTF-8](https://trello.com/c/DShzQztM/731-support-encodings-other-than-utf-8).

It's not a "restriction" so much as a missing feature -- it's not like we could show the file contents if we really wanted to, because the lack of encoding support affects _reading_ a file just as much as it affects saving it.

For your UTF-8 converter extension, it doesn't seem like you have to create a copy of the file.  You could replace the existing file with the converted result... and you could even automatically open it in the editor after that (invoke the `FILE_OPEN` command).  So it seems like it's already possible to create the extension behavior you're looking for.

Closing since the main feature is already tracked on our backlog, but please let us know if there's an extensibility hook Brackets is missing that makes it harder than expected to improve on your extension.

**Comment by Azakur4** [comment]
i dont know is this is a missing feature cuz in some past version of brackets this was possible almost in windows.

i already vote in backlog, but i write this issue cuz this feature is put in backlog like a year ago, that make me think that currently u are busy in features more important right now.

maybe open this restriction can help to another people work in this.

**Comment by peterflynn** [comment]
@Azakur4 Yes, your recollection is correct: in older Win builds we'd open any file even if it was completely garbled.  This was a bug.  As a fix, Brackets prevents opening any file where at least one character is guaranteed to be displayed incorrectly.  On Mac, Brackets has always behaved that way.

I don't think we want to go back to the old behavior where Brackets opened files and displayed them incorrectly (lots of people filed bugs on that).  We also don't want functionality/behavior that's only available on one platform.

This has the 6th highest number of votes in the backlog at this point, so we know it's important.  But it's also very costly to implement, supporting many popular encodings on three different native platforms.  One option is to leverage Node, which has several cross-platform libraries already, but it's an open question whether Node works reliably enough across Brackets installs for us to depend on it for core file IO; the upcoming [Brackets Health Data feature](https://trello.com/c/Uh3RpTnW/1396-brackets-health-data-report) will help us answer that question -- so you could think of that as one early step in the process.

**Comment by Jackbennett** [comment]
With 1.3 and right-click open offered on the default install, On Windows at least you may be interested in revisiting this. Or at least support the unicode that notepad lists (utf-16 is that?)

The reason being if I were to `"example file" > file.txt` Brackets can't open this. If I right click in the folder and create a new txt or save from opening notepad the default is ANSI and Brackets doesn't complain about that.

That's all, but for google in future, here's what you'd do in powershell:

`"example text" | out-file index.html -encoding utf8`
`... | convertTo-html`

I've put brackets in a secondary school classroom to try this term and I'm a bit worried about running into this. Dev tools is a hard sell to a teacher anyway so any friction at all could be a dealbreaker.
