### ISSUE TITLE
Exclusion set is being deleted

### ISSUE THREAD

**Issue by cfjedimaster** [adobe/brackets#10497]
I am testing exclusion sets, and when I reload Brackets, it deletes my exclusion set.

**Comment by redmunds** [comment]
Exclusion sets should be saved in your prefs, so check your brackets.json file. If you have project prefs, maybe they were save in project prefs instead (i.e. only exist for that project).

**Comment by cfjedimaster** [comment]
I do have a .brackets.json for this project, but it doesn't have any info
about exclusions in it. I should say - this is also a project with 30K+
files in it.

On Fri, Jan 30, 2015 at 10:17 AM, Randy Edmunds <notifications@github.com>
wrote:

> Exclusion sets should be saved in your prefs, so check your brackets.json
> file. If you have project prefs, maybe they were save in project prefs
> instead (i.e. only exist for that project).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adobe/brackets/issues/10497#issuecomment-72225886>.
>



-- 
===========================================================================
Raymond Camden, Web Standards Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by peterflynn** [comment]
@cfjedimaster Check the global brackets.json -- accessible via _Debug > Open Preferences File_.  Do you see `"fileFilters"` listed there?  Maybe also check in the OS to make sure you still have write permissions for that file.

Are you sure the exclusion set is actually getting lost?  I.e. when you open the dropdown in the Find in Files bar, nothing is listed?  Just want to make sure it's not actually some confusion stemming from the behavior in #10496 (e.g. exclusion set is saved but it appears not to be working since Find in Files is basically disabled entirely).

Lastly, please make sure the same issue still happens if you do _Debug > Reload Without Extensions_ (both when creating the exclusion set, and then again when reloading to see if it got saved).

**Comment by cfjedimaster** [comment]
Sorry I forgot this. I'm on a brand new machine and now I can't reproduce it. The other machine was used for *numerous* versions of Brackets, so maybe things just got borked along the way. I'm going to close it.
