### ISSUE TITLE
"New Brackets Window" should be moved the File menu instead of hidden away in the Debug menu.

### ISSUE THREAD

**Issue by scoot** [adobe/brackets#10529]
Having a new window function in the File menu is quite a normal thing across text editors and word processors, and usually comes with the keyboard shortcut of <kbd>CMD</kbd>+<kbd>N</kbd> or <kbd>CTRL</kbd>+<kbd>N</kbd>, possibly with a <kbd>SHIFT</kbd> modifier key.  Having it in the Debug menu is counter-intuitive.

**Comment by peterflynn** [comment]
Unfortunately, we have to recommend against that command for general use at this point. If you open the same folder in both windows (or a folder that is a parent / ancestor of the other window's folder) you can encounter serious bugs that make it easier to lose some unsaved work. You may also lose certain preferences changes that you make while two windows are open at once. And on Windows, keyboard shortcuts will only work in the first window.

For a reliable, official version of the feature, see this item on our feature backlog: [Multiple separate windows (official "New Window" command)](https://trello.com/c/YM0YySxX/679-multiple-separate-windows-official-new-window-command).  Please upvote that to help raise its priority.

In the meantime, I'd strongly encourage you to use the split view feature instead of the unsupported Debug command.
