### ISSUE TITLE
Brackets Pricing$$$

### ISSUE THREAD

**Issue by CEOofApple** [adobe/brackets#10532]
Its not an issue yet, but will Brackets remain open source, or will it cost money in the near future?

**Comment by codymaines** [comment]
Official statement from adobe representatives state that it is free indefinitely (https://forums.adobe.com/thread/1235571).

Since the project is open source, you can download it and build the executable yourself. Even if Adobe decided to monetize Brackets 2.0, this open source version would remain free.

**Comment by peterflynn** [comment]
As noted above, the MIT license means you will always be able to use this code for free.
