### ISSUE TITLE
Live preview doesn't work on frameworks

### ISSUE THREAD

**Issue by youssefdetovernickr** [adobe/brackets#10549]
Live previews doesn't work when you are using frameworks like Laravel. Example: In Laravel your pages are in a different folder called "resources/views". So lets say you have a PHP file located at: "resources/views/index.blade.php", live preview would redirect you to this file, however this file is visitable by any route you supplied. You must set a route and show the view on that route. Example, if you have the routing "home", the page is actually visitable at "(yoursite)/public/home" instead of "(yoursite)/resources/views/index.blade.php". 

I hope it's clear enough for people that don't know what Laravel is.

**Comment by peterflynn** [comment]
@youssefdetovernickr This issue is tracked on our feature backlog, here: [Make Live Development Work For Router-Based Server Technologies](https://trello.com/c/uKewlref/708-research-make-live-development-work-for-router-based-server-technologies).  Please upvote it to help raise the priority -- I'll close this bug to avoid duplication.
