### ISSUE TITLE
Chrome browser by default with Brackets.io

### ISSUE THREAD

**Issue by Deorro** [adobe/brackets#10562]
Chrome browser by default with Brackets.io

I just installed Brackets and I like a lot, but I have a little problem, maybe you can help me any.

When using the option "Live Preview" Chrome browser opens with the live document, but not shown me the extensions and bookmarks that I have installed on my browser.

This is when the window opens Brackets Live Preview:

http://prntscr.com/63d8m2

That is when I open myself (with extensions and bookmarks, but without automatic update), which is how I would like to have:

http://prntscr.com/63d8ru

How I can do so that when you open Chrome do as what I have configured?

Thank You.

Note: Use translator, sorry.

**Comment by redmunds** [comment]
@Deorro I think I answered your question in the comments of the [other issue that you commented on](https://github.com/adobe/brackets/issues/8653).

Since I made those other comments regarding Live Preview, we have added a new [Live Preview MultiBrowser option](https://github.com/adobe/brackets/wiki/Live-Preview-Multibrowser) that may behave more like you want, so give that a try.

**Comment by Deorro** [comment]
You can spend a video to enable this feature.

What I have understood is that this configuration can see the live preview in the current window you have open.

Can you tell me how to change livedev.multibrowser to true, where income?

**Comment by redmunds** [comment]
@Deorro In the [How to Use Brackets document](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets), look in the [Preferences section](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences) to see how to manually set preferences.

**Comment by peterflynn** [comment]
Closing since I think the question has been answered.  The current behavior of Live Preview (launching in a separate Chrome profile) is unavoidable, per #8653; the future Multi-Browser Live Preview does not have this issue; and the instructions linked above explain how to enable Multi-Browser Live Preview.
