### ISSUE TITLE
New release tasks for release 1.3

### ISSUE THREAD

**Issue by prksingh** [adobe/brackets#10578]
### Checklist for starting a new release cycle

- [x] \(Team) All unnecessary branches deleted from GitHub repos.
- [x] \(prksingh) \(Win) Check Live Development feature(s) with Chrome (beta) - in case a new beta release is available. See also: [googlechromereleases](http://googlechromereleases.blogspot.com/).
- [x]  \(prksingh) \(Mac) Check Live Development feature(s) with Chrome (beta) - in case a new beta release is available. See also: [googlechromereleases](http://googlechromereleases.blogspot.com/).
- [x] Decide whether to Integrate new CEF
- [x] \(rroshan1) Check wiki for spam (MUST do on Mac!)

**Comment by prksingh** [comment]
We are updating codemirror next week, which should fix #10371

**Comment by MiguelCastillo** [comment]
@prksingh Please let's integrate the new CEF!

**Comment by MiguelCastillo** [comment]
@prksingh this is why we should update our CEF https://github.com/adobe/brackets/issues/10315

/cc @peterflynn @redmunds

**Comment by peterflynn** [comment]
@MiguelCastillo I don't think a new CEF is in scope for 1.3 -- remember it took us over a _month_ to get the last update working, and in fact we're still not done with that last update on the Linux side.

We definitely want to keep taking newer CEFs, but I think 1.4 is the earliest we could realistically pick up a new one...

But also: #10315 only applies when dev tools are opened in a browser tab, which is sort of deprecated now and not what the Debug menu item does.  So it seems like a lower-priority issue since there's an easy workaround and you'd have to go out of your way to even hit the bug.

**Comment by MiguelCastillo** [comment]
@peterflynn let me ask you this.  in brackets, when you go to Debug -> Show Developer Tools, dev tools come up.  Currently, I cannot expand/collapse data in the console and in the elements tab.  Well, anything that relies on `getPropertyCSSValue` really...  That's fixed with a an updated CEF, right?

**Comment by peterflynn** [comment]
@MiguelCastillo What platform are you on?  On Mac & Windows, it should not open a browser tab when you choose that menu item.

**Comment by MiguelCastillo** [comment]
I am on Mac... Yeah it opens a browser tab.

**Comment by MarcelGerber** [comment]
Could you just try typing `navigator.userAgent` into the developer tools' console and copy what you get?
I assume you either use an old build or a misconfigured custom build of Brackets Shell.

**Comment by MiguelCastillo** [comment]
@MarcelGerber this is what I get
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by MarcelGerber** [comment]
That's not what I meant. I meant requesting Brackets' userAgent string by typing into its console.

**Comment by MiguelCastillo** [comment]
@MarcelGerber well, i gave you what you asked me to give you...  I typed `navigator.userAgent` in the console of the dev tools that come up when I go to Debug -> Show Developer Tools.  Can you please tell what other console there is?

**Comment by MarcelGerber** [comment]
Hm, yours is clearly your browsers User Agent string. You did that in the DevTools' Console tab (like below), correct?
![image](https://cloud.githubusercontent.com/assets/2641501/6987640/9fcf0d06-da49-11e4-9c6f-17fc73c177c9.png)

**Comment by MiguelCastillo** [comment]
![screenshot 2015-04-03 15 41 24](https://cloud.githubusercontent.com/assets/1457701/6987697/f762eab0-da17-11e4-9bd2-c0b9b59da55a.png)

**Comment by MarcelGerber** [comment]
Yeah, that's the _wrong_ console (it's your browsers one). Go to the console tab and type it there.

**Comment by MiguelCastillo** [comment]
HA! sorry yeah you are right... I completely forgot that I was debugging the developer tools!

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Brackets/0.42.0 Chrome/29.0.1547.80 Safari/537.36"

**Comment by MarcelGerber** [comment]
Yep, that's the culprit. You got a Brackets Shell build from Release 0.42.
Either [download the latest one](https://github.com/adobe/brackets/releases/download/release-1.2/Brackets.Release.1.2.dmg) or build it yourself, and your problem will be fixed.

**Comment by MiguelCastillo** [comment]
@MarcelGerber AH! ok cool, thank you!

**Comment by rroshan1** [comment]
Completed the last pending task- Check wiki for spam.
Closing the task.
