### ISSUE TITLE
Current selection  re-rendering in the file tree is visibly delayed on scroll

### ISSUE THREAD

**Issue by busykai** [adobe/brackets#10573]
![scroll-issue](https://cloud.githubusercontent.com/assets/3368515/6151995/86e1eac6-b1f8-11e4-9d99-c45b2d4ced02.png)

To reproduce:
0. Expand a project tree or resize the editor so that the scrolling would be enabled in the file tree.
1. Select a file in the file tree.
2. Grab the vertical scroll bar and scroll back and forth.

Result: the overlay part of the selection stays at its position until the entire react finishes rendering the entire tree.

See the attached image. The scroll overlay part of the current selection is not re-rendered until the entire file tree is re-rendered.

**Comment by busykai** [comment]
Perhaps we could hide the selection extension on componentWillUpdate and make it visible again after rendering is finished.

**Comment by peterflynn** [comment]
Before the new project tree & splitview stuff landed, there was no lag at all -- so it should be possible to keep it in sync fast enough to look fine.  I think a deliberate decision was made to debounce the drawing in the new implementation, but I'm not sure why since there was no performance problem with it in the past...

**Comment by busykai** [comment]
@MarcelGerber, as soon as I recover my dev environment, I'll validate and close this. Thanks for the fix, it was annoying!
