### ISSUE TITLE
Suggestion: ability to cancel color change

### ISSUE THREAD

**Issue by warpdesign** [adobe/brackets#10631]
When pressing CTRL+E to edit a color in CSS, a nice color editor is brought, changing color in real time.

The thing is once you change it, there's no way to roll back your change and go back to the value it was before pressing CTRL+E.

For example when pressing escape or when clicking on a cancel button.

**Comment by sprintr** [comment]
Why not press `Ctrl+Z` to undo changes.

**Comment by warpdesign** [comment]
I can do that indeed. But I find it disturbing that pressing Escape doesn't do it by default.

It means you must accept the changes, and then undo it with CTRL+Z.

**Comment by peterflynn** [comment]
@warpdesign The inline colorpicker isn't a modal dialog: changes are "accepted" the moment you drag the slider, in the sense that you're immediately modifying the actual text of the document.  This is very powerful coupled with Live Preview, because the webpage will update continuously as you're dragging.  You can also open multiple pickers at once, and intersperse editing among them (or even edit directly in the text editor while they stay open).

If you press Ctrl-Z while focus is in a colorpicker, it will revert to whatever the original color was when it was opened -- regardless of how many edits you've made throughout the document in the meantime... you may find that useful.

I think we'd be open to having some sort of modifier like Ctrl-Escape that would invoke that revert operation while closing the colorpicker, instead of just closing it without reverting its changes as regular Escape does.  Do you feel that's necessary in addition to the existing Ctrl-Z revert feature?

**Comment by MarcelGerber** [comment]
@peterflynn What you're describing (`If you press Ctrl-Z while focus is in a colorpicker, it will revert to whatever the original color was when it was opened`) doesn't apply (any longer) -- nothing happens when pressing Ctrl-Z while focus is in a Color Editor.

**Comment by warpdesign** [comment]
@peterflynn I definitely feel something like this is needed, yes.

Since the changes are made in realtime (and indeed it's usefull for Live Preview for example), I really think having some way to cancel editing is a need.

**Comment by peterflynn** [comment]
@MarcelGerber Ah, good catch -- this was broken a long time ago when native menus were introduced.  Originally filed as #4989, which was folded into a more general [user story about context-sensitive keyboard shortcuts](https://trello.com/c/I07x1pO0/1002-more-flexible-key-event-handling-contextual-scoped).

One [earlier proposed fix](https://github.com/adobe/brackets/pull/5070) has the one existing Undo handler cover all three cases (editor focused: trigger CM undo; inline widget focused: plumb event to it; something else focused: allow browser default).  Although originally rejected as too specific, I'm not sure it's that awful. It could also be cleaned up by adding an undo hook into the InlineWidget API.  Is it worth doing that work as an interim fix?  Not sure.

In the meantime, @warpdesign -- you can also work around this by just clicking the color swatch for the original color, found in the upper-right of the colorpicker.  That will also revert the color to its original value.

**Comment by peterflynn** [comment]
Closing as a duplicate.  I've added some more notes to the user story.
