### ISSUE TITLE
"Run Tests" always greyed out.

### ISSUE THREAD

**Issue by keir-rex** [adobe/brackets#10640]
I'm trying to follow the instructions here [1] in order to run unit tests against my extension. Problem is: the menu item is always greyed out - even when I load a default extension (with unittests.js in root).

Any ideas what might be the cause?

[1] https://github.com/adobe/brackets/wiki/Extension-Unit-Tests

**Comment by redmunds** [comment]
@keir-rex Yes, *Debug > Run Tests* is always disabled on installer builds because they do not include the test files. You'll need to clone Brackets repo to run the tests. The [How to Hack on Brackets page](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets) explains how to clone Brackets.
