### ISSUE TITLE
open folder via terminal 

### ISSUE THREAD

**Issue by rubensfernandes** [adobe/brackets#10657]
open brackets with folder via terminal like "subl ." with "brackets ."

**Comment by sbruchmann** [comment]
If you are using OS X and npm, then you are lucky: https://www.npmjs.com/package/bkts

**Comment by peterflynn** [comment]
On Windows, this works already -- just add the install location to your path and you can invoke `Brackets` at any time.

For Mac & Linux, it doesn't work yet -- this is tracked on our feature backlog: [Open File/Folder from Command Line on Mac](https://trello.com/c/dRNqhd2L/349-open-file-folder-from-command-line-on-mac).  Please upvote it there, since I'll close this bug to avoid duplication.  As noted above, for Mac there's a simple shell script you can use as a workaround in the meantime.

**Comment by rubensfernandes** [comment]
vote done! Thanks!
