### ISSUE TITLE
Files don't update when edited outside Brackets

### ISSUE THREAD

**Issue by floede** [adobe/brackets#10662]
If I have a file open in Brackets and edit it with another program or with Grunt tasks for instance, the change doesn't appear in Brackets, and indeed I can't even make it update, except by closing Brackets completely.
Only if I try to save the file in Brackets, do I get an alert.

I'm on Windows 7 and 8.

**Comment by redmunds** [comment]
@floede If I open a file in Brackets *and do not edit it** and then edit it with another program *and save*, then I do see the change in Brackets. But, if I edit a file in Brackets *and do not save it* and then edit/save with another program, then I see what you describe. Is that what you're seeing? If so, then that's the currently expected behavior.

If not, then what exactly would you expect? Are there any other editors that do what you expect?

**Comment by peterflynn** [comment]
@redmunds You should see an alert _immediately_ in that case though, rather than only later on when you try to save from Brackets.

@floede What type of file system is your project stored on?  Anything unusual like a thumb drive, network share, or symlink / NTFS junction point involved?

**Comment by floede** [comment]
@redmunds @peterflynn It would seem that I had neglected to update Brackets.

I'm now running the latest version, and I can't replicate the behavior I saw earlier. 
I see an immidiate reaction in Brackets either way, which is what I expected.

**Comment by peterflynn** [comment]
@floede Thanks!  If it starts happening again, please select _Debug > Show Developer Tools_ and check to see if the console contains any errors.

**Comment by redmunds** [comment]
Yes, I'm seeing that too. I think my initial test was to make an edit in external file, delete (*not* undo) it, and then Save so timestamp was updated, but actual file contents did not change.
