### ISSUE TITLE
Add ability to leave / jump out of closing characters " ' ) ] } with Tab key like in Eclipse

### ISSUE THREAD

**Issue by dag0310** [adobe/brackets#10664]
Typing each closing character manually does NOT replace this functionality, because it is a lot less conventient to type. It feels like one of those Quick Time Events in video games where you have to press the keys in correct order if you have something like "}] when you could just press TAB three times instead.

**Comment by MarcelGerber** [comment]
I don't have Eclipse installed, so just one question:
What does Eclipse do in a situation where, say, `}` is the first character of a line? Does it indent or does it "jump out"?

Also, I tried Notepad++, Sublime Text 3 and Netbeans to see if they have this feature (by default), and neither of them had it. To me, overloading the Tab key doesn't sound like the best idea ever as it may disturb you when you really need to insert a Tab.
That is, is there any advantage of pressing Tab instead of the right arrow key to move the cursor to the right?

**Comment by dag0310** [comment]
Hi, thanks for replying so fast!

As for your first quesiton: it indents.
You are right, I have also used many IDEs before and Eclipse was the only one with this feature.
Overloading is not a problem, because when do you really ever need to insert an actual tab? Normally you want something like \t, but never an actual tab, except for indentation of course, which would no be affected naturally. And you can still insert the tab by moving to the left and pressing TAB. Right arrow key is just as bad or even worse than having to re-type the end characters manually (which Eclipse also supports) in my opinion, because I have to move my hand from the default typing position. Pressing TAB feels very natural and especially when writing JavaScript makes creating objects and arrays a joy. I know it may sound like a very minor improvement or even useless, [but if you typed it yourself you would understand ;-)](https://drive.google.com/file/d/0B9jb4cT933bVcTA1XzByWndrRUk/view?usp=sharing)

At least it should be added as a configurable setting which is disabled by default IMO.

**Comment by peterflynn** [comment]
@dag0310 Could you detail more specifically when you would expect pressing Tab to indent vs. when you'd expect it to jump to the closing brace/paren char?  Since the cursor is almost always going to be inside _some_ pair of braces/parens, it seems like it'd be hard for a user to predict when Tab will do what...

One way to tackle this would be to [write an extension](https://github.com/adobe/brackets/wiki/How-to-Write-Extensions) demonstrating the behavior you're looking for -- that's a good way to work through all the edge cases.  Then if it proves popular, we could go ahead & merge the code into core.

**Comment by dag0310** [comment]
@peterflynn Writing an extension sounds like a good idea, so I'll probably give it a try. I expect it to jump outside only if the cursor is right next (left) to the closing character. Eclipse shows a vertical bar after the closing char to indicate that pressing Tab would make the cursor jump outside of it. I've used Eclipse extensively and have never had a problem with this feature, so it's probably a good idea to emulate this behavior.

**Comment by dag0310** [comment]
**[Tab Out](https://github.com/dag0310/tab-out)** is done and uploaded to the [Extension Registry](https://brackets-registry.aboutweb.com/) :-)
