### ISSUE TITLE
Brackets-icon disappears from the taskbar when updating (Windows only?/Brackets-shell)

### ISSUE THREAD

**Issue by petetnt** [adobe/brackets#10687]
This issue has been there since I can remember but it just happened to me again when updating to 1.2.

Steps to reproduce:
1. Install Brackets <1.2
2. Pin Brackets to task bar
3. Update Brackets to 1.2.
4. Taskbar icon is now blank (the shortcut works properly though of course)

![hmm](https://cloud.githubusercontent.com/assets/7641760/6480391/ecce8dd0-c25b-11e4-97a0-1df7bf6b90e3.png)

There are multiple ways to work around this including:

1. Pinning it to Start menu again
2. Killing explorer.exe (you might have to delete `%userprofile%\AppData\Local\iconCache.db` by hand) and restarting it
3. Restarting your PC

I am a bit fuzzy on how the `iconCache` on Windows works, but it should help if the installer didn't remove the icons when updating (and instead just overwrote the icons if needed, after which the icons would update eventually if they were changed).

**Comment by MarcelGerber** [comment]
I'm 100% sure this was already filed, but I can't seem to find it...

**Comment by petetnt** [comment]
Thought so too but couldn't find one either (searched closed issues too). Hmm..

**Comment by MarcelGerber** [comment]
Ha, found it using Google: #6297

**Comment by le717** [comment]
This can be closed in favor of the aforelinked #6297 (in order to reduce issue duplication). I have extensively documented this bug in https://github.com/adobe/brackets/issues/6297#issuecomment-35035371 and given a rough fix in https://github.com/adobe/brackets/issues/6297#issuecomment-41357639, but it's kinda shaky ground as to if this practice of automatically recreating the taskbar icon is against MS guidelines (as pointed out in that issue).

**Comment by petetnt** [comment]
Yup! Thanks!
