### ISSUE TITLE
.sass Syntax Highlighting got worse

### ISSUE THREAD

**Issue by JonathanBergson** [adobe/brackets#10692]
Updated the Brackets to 1.2, then I started to have problems with the syntax .sass files.
To solve the problem had to go back to version 1.1.

**Comment by le717** [comment]
Can you post screenshots of the syntax highlighting issues you are having in v1.2 vs the working v1.1? Also, just to clarify, are you using the Sass or SCSS syntax? Remember, Brackets does not have official support for classic (braceless) Sass, though I don't think that would syntax highlighting, as that is controlled by CodeMirror.

**Comment by peterflynn** [comment]
Brackets does have syntax highlighting for classic .sass built-in.

@JonathanBergson Please post a code snippet -- and can you also check if the same problem appears when you paste that code here: http://codemirror.net/mode/sass/  Thanks!

**Comment by le717** [comment]
> Brackets does have syntax highlighting for classic .sass built-in.

I know, that's why I was saying I doubt official classic sass support (code hints, live reload, etc) would effect syntax highlighting. It seems I left out a word in my reply.

**Comment by JonathanBergson** [comment]
@peterflynn 
![codemirror - brackets v1 2](https://cloud.githubusercontent.com/assets/6494405/6496413/47210082-c2b2-11e4-933e-6b0d7fe6df0e.png)
![codemirror - brackets v1 1](https://cloud.githubusercontent.com/assets/6494405/6496414/4728c86c-c2b2-11e4-94a7-b7038e866f93.png)

**Comment by JonathanBergson** [comment]
first image: Brackets v1.2
second image: Brackets v.11

**Comment by le717** [comment]
@JonathanBergson Just to rule out any external factors, is the same issue present when you reload without extensions (_Debug> Reload Without Extensions_)?

**Comment by JonathanBergson** [comment]
@le717 Yes, the problem continues.

**Comment by peterflynn** [comment]
I can repro this too.  I think some of this was an intentional change in the token types returned by CodeMirror SASS mode:

* Property enum values changed from `atom` to `attribute` -- so they used to be the same color as block headers, and now they're the same color as number values.  (This is still inconsistent with CSS/LESS/SCSS modes though, where all three of those things have separate, distinct colors).
* Property name prefixes that are the start of an indented block changed from `property` to `atom` -- so they used to be the same color as full property names, and now they're the same color as full-selector block headers.

However, that doesn't explain full property names (like `float`) losing their color.  Those are token type `property` in both releases, so I don't understand why those changed.

**Comment by JonathanBergson** [comment]
@peterflynn this is one of my files, the differences are greater.
First image: Brackets v.11
![01 - brackets v1 1](https://cloud.githubusercontent.com/assets/6494405/6497048/51d0f102-c2b9-11e4-8014-43617f852e04.png)
Second image: Brackets v1.2
![01 - brackets v1 2](https://cloud.githubusercontent.com/assets/6494405/6497050/5a0efecc-c2b9-11e4-9f1d-8510fc79464d.png)

**Comment by peterflynn** [comment]
Turns out that last mystery was a typo in the latest version of CodeMirror. I posted a fix here: codemirror/CodeMirror#3116.  That will make the property names purple again.

**Comment by JonathanBergson** [comment]
This fix has been published for Brackets? Or should I wait for the next release?
Thank you for listening.

**Comment by le717** [comment]
@JonathanBergson The fix @peterflynn submitted to CodeMirror has been merged, and it should be present in the next release. :)

**Comment by JonathanBergson** [comment]
Okay, thank you. I look forward to next version.

**Comment by JonathanBergson** [comment]
sass.js found the file and made the change.
