### ISSUE TITLE
Some key binds are repeated for different platforms

### ISSUE THREAD

**Issue by PlanetVaster** [adobe/brackets#10704]
Some key binds are repeated just with the extra platform: "example" tags, is this how it's supposed to be considering the keys are the exact same. 
![capture2](https://cloud.githubusercontent.com/assets/11320438/6519297/15b22fac-c380-11e4-960c-29e6317305d4.PNG)
![capture](https://cloud.githubusercontent.com/assets/11320438/6519298/15bb303e-c380-11e4-8a37-b4b8dffed577.PNG)

**Comment by PlanetVaster** [comment]
Wouldn't it be cmd-space?

**Comment by le717** [comment]
To my understanding, the Ctrl key is automatically remapped to Cmd on Mac, so one only has to write the shortcut once (as a Windows shortcut) and it automatically converted to a Mac shortcut. @RaymondLim I'm not familiar with the shortcut behavior, can you provide more details here?

**Comment by peterflynn** [comment]
This is by design.  All of the shortcuts you've shown differ between OSes; the first one listed is the default shortcut (in these cases shared by Win & Linux) and the other is a platform-specific override.

For the first two examples: Ctrl-Shift is not the same as Cmd-Ctrl (note no Shift in the second one)

The last example is a bit tricker: Ctrl in a shortcut is normally converted to Cmd automatically on Mac.  In order to override this and ensure Ctrl is used even on Mac, you use a platform-specific shortcut to disable the automatic conversion. This is [documented on KeyBindingManager](https://github.com/adobe/brackets/blob/release-1.2/src/command/KeyBindingManager.js#L839).  The reason Mac needs to be Ctrl-Space instead of Cmd-Space is that Cmd-Space is reserved by the OS for launching the Spotlight search feature.

**Comment by PlanetVaster** [comment]
Ok thx for the info I understand now
