### ISSUE TITLE
Allow explicitly specifying file 'language'regardless of file extension

### ISSUE THREAD

**Issue by michaelbadichi** [adobe/brackets#10732]
this is especially helpful when creating a new file or opening a temporary edit window
you won't get any language feature like syntax highlighting until you save the file with the right extension which is very annoying

**Comment by prksingh** [comment]
If you are running brackets from source, you can fix this by commenting the following statement in https://github.com/adobe/brackets/blob/master/src/editor/EditorStatusBar.js 

`languageSelect.$button.prop("disabled", doc.isUntitled());`

Brackets uses tern to generate code hints for a file using other files in the same directory. Since this information is not available for an untitled file, code hints will not work for the untitled file, but syntax highlighting will work.

**Comment by peterflynn** [comment]
A _number_ of Brackets features will break if you were to change the language of an Untitled document, including the JS code hints mentioned above.

Please upvote [Switch language / type of Untitled documents](https://trello.com/c/CNXuU4TY/1369-switch-language-type-of-untitled-documents) on our feature backlog for this to be officially supported.  I'll close this bug to avoid duplication with what's already tracked on the backlog.
