### ISSUE TITLE
Live Preview Not Works

### ISSUE THREAD

**Issue by torreslucas13** [adobe/brackets#10751]
Browser: Google Chrome Version 41.0.2272.89 m
Brackets Release 1.2 build 1.2.0-15697 (release 8f82e2a97) 
build timestamp: Sun Feb 22 2015 22:34:56 GMT-0800
![issue1](https://cloud.githubusercontent.com/assets/8942972/6658489/805cd35e-cb49-11e4-961c-a8f74fd0ffbe.png)

**Comment by prafulVaishnav** [comment]
Can you try https://github.com/adobe/brackets/wiki/Troubleshooting#livedev. Also make sure you have tried Debug > Reload Without Extensions to make sure it is not because of bugs in any extensions. Also can you share is there is any error on console (Debug > Show Developer Tools) Let us know if problem persists.

**Comment by abose** [comment]
Closing as inactive thread.
Please reopen if you run into this again.
