### ISSUE TITLE
Main menu bar Find > Find In / Replace In are confusing or useless

### ISSUE THREAD

**Issue by petetnt** [adobe/brackets#10754]
Win 8.1, Brackets 1.2. release.

Steps to reproduce:
1. Click a folder in File Tree
2. Folder collapses/uncollapses but isn't selected
3. Can't use "Find in Selected File/**Folder**" or "Replace in Selected File/**Folder**"

**Comment by redmunds** [comment]
@petetnt Yes, this is by design. To use "Find in Selected File/Folder" or "Replace in Selected File/Folder", right-click on FIle/Folder in file tree and choose it from the context menu.

**Comment by petetnt** [comment]
Oh right! That explains why I couldn't figured out how to do it today when I was certain I had been able to do it before... most likely because I didn't check the context menu. Closing as it's by design. Thanks @redmunds

**Comment by peterflynn** [comment]
Reopening since it seems like we shouldn't have those items in the menu bar if that can't actually be sensibly invoked from there.  Looks like those menu items were added in #7488 but without any real discussion.

**Comment by petetnt** [comment]
Actually the new title matches the situation better...

In the menu bar, `Find/Replace in selected file` is pretty silly as it's exactly the same as just `Find`. Then again for `Find/Replace in selected folder` is something that I can think use for, especially when `Find/Replace in Files` defaults to project root.

But then again, all of those features are available when right clicking the file tree items, but discoverability is a bit lower (in my opinion, that is).

**Comment by nethip** [comment]
@peterflynn Yes I think this makes sense to remove these menu items.

**Comment by redmunds** [comment]
@petetnt `Find in selected file` is a little different from `Find` (in a single file) in that you see all of the results in the panel below.

**Comment by petetnt** [comment]
@redmunds ha, you are correct! Can't believe I missed that too..

**Comment by lkcampbell** [comment]
This issue is coming up because the new version of the project tree does not highlight the folders when they are opened or collapsed. Not sure when this changed, probably with the React update of the project tree. I looked at a much older version of Brackets (Sprint 37) and the folders use to highlight when we selected them. Without that highlighting, a menu version of this command makes no sense anymore.

**Comment by prksingh** [comment]
Instead of removing the menu, would it be better to allow folders to be selected in file tree and populate the selected folder by default on `Find/Replace in selected folder`? If no folder is selected, we could default to the whole project or the current file

**Comment by peterflynn** [comment]
@prksingh We deliberately removed the ability to select folders earlier, since it presents usability issues of its own (e.g. selection highlight no longer reflects what file is shown in the editor area), and a number of other tools also don't let you select folders.  Since the same feature is already accessible via right-click, I think it's better to just remove the confusing menu items for now.  (And searching the current project is already accessible via regular Find > Find in Files, and searching current file only is accessible via regular Find > Find).

**Comment by prksingh** [comment]
@peterflynn Got it! Thanks. Removed the two confusing menu items

**Comment by petetnt** [comment]
:+1:
