### ISSUE TITLE
Integreted Live Preview

### ISSUE THREAD

**Issue by Timodz** [adobe/brackets#10766]
It Will be nice if The Application has an Integreted Live Preview So users Dont have to go each time to the browser so  work and test in Brackets

**Comment by prksingh** [comment]
This is being tracked as a trello card: https://trello.com/c/YG0BBlrl You can upvote the card to increase its priority.

This feature has not been high on brackets priority though, as mentioned in the card:

"One of our central ideas when creating Brackets is that there should not be a 'design view'. We believe that designs and code are best /displayed run in their target environment, not in an emulator.

However, Brackets is technically built on top of Chromium (the open source core of Chrome). So technically, a preview window inside of Brackets would be nearly identical to Google Chrome.

But there are some exceptions. We strip out a few parts of the Chromium project that have licenses that are incompatible with Brackets. Unfortunately, that means our built-in version of Chromium doesn't support HTML video or audio (since those codecs aren't covered under an MIT-compatible license)."

**Comment by prksingh** [comment]
Closing to avoid duplication
