### ISSUE TITLE
Possible API for Cut/Copy in-browser verison

### ISSUE THREAD

**Issue by le717** [adobe/brackets#10905]
Chrome 43 (joining IE10+ and Opera 29+) adds support for programmatic cut/copy using  `Document.execCommand()` [(source)](http://updates.html5rocks.com/2015/04/cut-and-copy-commands). This API might be able to be used for cut/copy in the distant future in-browser version of Brackets. Filing this more as a "make a note of that on the backlog" issue. ;)

**Comment by peterflynn** [comment]
Probably most related to this story: [Clipboard Cut/Copy/Paste in Editor Context Menu](https://trello.com/c/ZriVEu50/935-clipboard-cut-copy-paste-in-editor-context-menu)

**Comment by peterflynn** [comment]
Actually, this is probably not something we could use since it deliberately doesn't support paste.  I've added a note on the Trello card though, so we can check back later to see if they decide to expand the scope of this feature.  Closing since there's nothing we can do for now.

**Comment by le717** [comment]
Except wouldn't paste be rather easy to implement? When the paste command is sent, get the cursor location and using CM's insert method (or anything else) to inject the text right there? It might be that paste was deliberately for that purpose: we already have most (if not all) the ability to code in a paste ourselves (although I agree, it would be nice if the API supported paste).

**Comment by peterflynn** [comment]
That part is indeed easy -- in fact, that's exactly how CodeMirror works already.  The hard part is _triggering_ the paste command in the first place.  Browsers will trigger it natively when the user hits Cmd-V or selects Paste from the _native_ menu bar; but JS cannot trigger paste on its own (e.g. from an HTML toolbar button or context menu).  In regular browsers, it would be a serious security problem if JS could do this whenever it wanted, since users may have sensitive info on the clipboard that they didn't intend to share with every random website out there.

Since we _do_ trust the JS code that makes up Brackets, we could add our own native APIs to brackets-shell that lets JS trigger the native action.  But that's a bunch of work we'd have to do -- that's what the Trello card refers to.

**Comment by peterflynn** [comment]
So to clarify the original title -- cut/copy/paste _already_ in-browser today if you use the keyboard or the native menu.  We just couldn't offer an HTML menu (e.g. our own Edit menu) with menu items for cut/copy/paste.
