### ISSUE TITLE
How do i run brackets in browser

### ISSUE THREAD

**Issue by awebdeveloper** [adobe/brackets#10966]
i would like to use chrome to develop instead of using brackets native shell . All articles that i found are old and outdated could some one point me the way.

**Comment by Equinox** [comment]
As far as I know, [Bramble](https://github.com/humphd/brackets) is an attempt at exactly that. 
An example being [here](http://humphd.github.io/brackets/dist/).

**Comment by awebdeveloper** [comment]
i mean run my local files

**Comment by abose** [comment]
Please upvote this feature in https://trello.com/c/o5nf9nHc  and https://trello.com/c/61ChEQmJ 

If you are planning to port this as a chrome app alone[as against a generic browser web app], you could start by mapping the native shell API's to chrome API's. 

You could also start discussions in the brackets community forum at https://groups.google.com/forum/#!forum/brackets-dev So that interested community members would help you out in you effort.

**Comment by humphd** [comment]
FYI: you can play with our browser fork here as we add things:
* https://mozillathimblelivepreview.net/bramble/dist/index.html?ui=1 (with full UI)
* https://mozillathimblelivepreview.net/bramble/dist/ (with a bunch of UI turned off for our use case)
* https://bramble.mofostaging.net (our staging server that integrates this into Thimble, and uses the static site above in an iframe)
