### ISSUE TITLE
Core: Overwrite external changes works incorrectly now

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets#10983]
Steps:
1. Launch Brackets and open a project
2. Open a file to working set and edit this file without saving
3. Edit the same file from OS without saving
4. Back to Brackets and click this file

Result:
On Win, nothing happens. On Mac, the External Changes dialog says external modified message 
"<span class='dialog-filename'>{0}</span> has been modified on disk outside of {APP_NAME}, but also has unsaved changes in {APP_NAME}.Which version do you want to keep?"

Expected Result:
Overwriting warning dialog should show up, which means that External Changes dialog should say external modified warning
"<span class='dialog-filename'>{0}</span> has been modified on disk outside of {APP_NAME}.Do you want to save the file and overwrite those changes?"
( Please ignore this original message:"<span class='dialog-filename'>{0}</span> has been deleted on disk outside of {APP_NAME}, but has unsaved changes in {APP_NAME}. Do you want to keep your changes?" )

ENV: Win7 and Mac 10.8 English OS
Build: 1.3.0-16017

**Comment by rroshan1** [comment]
@julieyuan Looks like your OS editor on MAC has the **AutoSave option enabled**. As such, Brackets identifies that it has a set of changes while the file has been modified on disk outside Brackets. This is as per our expectations. Can you please disable the auto save option OR use an editor without AutoSave and then try. 
The AutoSave option makes other Brackets-like editors like Sublime also behave in the same way. I have verified this.
I am not sure why you would expect a deleted on disk dialog for external edit changes. Looks like you meant modified instead of deleted.

**Comment by rroshan1** [comment]
Without AutoSave option in an external editor, the file will not be modified on disk externally. As such, Brackets need not bother about it as you see in Windows.

**Comment by rroshan1** [comment]
@julieyuan If you are fine with the conclusions, shall we close this issue?

**Comment by julieyuan** [comment]
@rroshan1 Thanks for the info. Yes, it should be the modified message instead of deleted. Updated the expected result. But I still have one question, if the behavior on win is expected, the overwrite dialog won't be used anymore, right?

**Comment by rroshan1** [comment]
Sorry for the late reply.
For your query- Yes, you are right. Currently, if there are no unsaved changes in a file opened in Brackets editor and changes are made externally on disk, it just picks up the latest file from disk without showing any dialog.
I will review the code and let you know later as when to expect the overwrite dialog.
Closing the issue for now.
