### ISSUE TITLE
Brackets, color customization

### ISSUE THREAD

**Issue by Hiei16** [adobe/brackets#11024]
Hi,

I recently adopted the IDE Brackets which is similar to Sublime Text that I find a little more convenient to use.

No theme suited me, so I create one. I succeed to managed 90% of the theme with that kind of code (need theme extension to create):

.CodeMirror[doctype=php] .cm-comment {
    color: #F90 !important;
}

.CodeMirror[doctype=css] .cm-comment {
    color: #999 !important;
}

For example, here I specifies the color for comment once in a PHP file and once in a CSS file.

But when I have a HTML class (in a file.php) the value of class = "value" takes the same color as a value in PHP: $_SESSION ['value'] because the doctype is for PHP files.

Second problem, brackets considers echo as a function, so it assigns the same color for both, I wish I could give a different color.

Here's the code that I put to the class & the PHP variable:

span.cm-string{ color: #cc0000; }

And the code for functions/echo:

span.cm-keyword{ color: #00F; }

Thanks for anwers! :)

**Comment by abose** [comment]
hi @Hiei16 the issue tracking page for brackets is usually reserved for tracking bugs/issues. 
you could refer to https://github.com/adobe/brackets/wiki/Themes and https://github.com/adobe/brackets/wiki/Creating-Themes pages to get some introduction on the topics.
If you are looking for help relating to specifics in brackets/other general discussion topics, you could post this topic in brackets discussion forum at  https://groups.google.com/forum/#!forum/brackets-dev 

I am closing the issue here.
