### ISSUE TITLE
Brackets unusable but still responsive - does not open files or close properly

### ISSUE THREAD

**Issue by chrisjmendoza** [adobe/brackets#11051]
Last week, my Mac failed to go to sleep and ran out of battery. Brackets and some other programs were open at the time. The next day, I plugged it in and turned Mac back on. Everything works except for Brackets now. I can open it, and that's it. It doesn't show any of my files, it won't open any files, and doesn't close. I have tried uninstalling and reinstalling it, installing the prior 1.2 brackets, and also looked at the Application Library/Brackets folder (which wasn't there) to delete possible bad preferences. I cannot load it without extensions. I have created a short video to show exactly how it is behaving. File located on my site [here](http://cjinseattle.com/media/brackets-test.mov). I have also pulled up the Brackets console in Chrome in the video so you can see the specific errors it's giving me. 

From Chrome console: (localhost:9234)
![screen shot 2015-05-04 at 12 38 29 pm](https://cloud.githubusercontent.com/assets/1704433/7460868/fa909088-f25a-11e4-9a23-746e0e9decf9.png)

**Comment by ryanstewart** [comment]
hey @chrisjmendoza if you clear out your `~/Library/Application Support/Brackets/cef_data/` folder, does that work?

**Comment by chrisjmendoza** [comment]
As I mentioned before, there is no such folder in my application support
folder. Even when I uninstall and reinstall, I never see it.

**Comment by nethip** [comment]
@chrisjmendoza From the logs above, I can see that the `Brackets` folder is present inside `~/Library/Application Support` on your system as Brackets is still able to reference a file from there (`brackets-paste-and-indent/main.js`).  Can you check again if the folder, `Brackets` is present at `~/Library/Application Support/`. If present, please rename this to anything other than `Brackets`, so that Brackets can start with fresh settings. Note that if you delete this `Brackets `folder, you will loose any custom preferences that you would have customized Brackets with, if at all and also extensions you would have downloaded. So just renaming should be good. Later, once you have successfully managed to lauch Brackets, you could copy back the extensions from the renamed folder back to `~/Library/Application Support/Brackets/extenions/user`.

**Comment by nethip** [comment]
@chrisjmendoza And make sure you are referring to user's `~/Library/Application Support/` folder rather than `/Library/Application Support/` folder. Best way to make sure of that is to type in `Cmd-Shift-G` shortcut in `Finder` and type in `~/Library/Application Support/` in the `Go To The Folder` dialog.

**Comment by chrisjmendoza** [comment]
FINALLY someone pointed me to the right place. No one ANYWHERE ever said to look in my user application support (I'm not new to PCs, just Macs, so I'm still figuring out the little these like these). I found the folder, deleted it (I can always get my extensions again, not important), reinstalled and voilá! @nethip THANK YOU for helping me to fix this. Case closed now.

**Comment by redmunds** [comment]
@chrisjmendoza FYI, in unix (which is used by Mac) `~` means *user folder*.

**Comment by chrisjmendoza** [comment]
That'll be handy to know. That also explains a lot of tutorials I've read.
Thank you!

**Comment by MarcelGerber** [comment]
Closing.

**Comment by mrthappy** [comment]
helllo people,
can anyone out there help me with me out with bracket , i tend to get this popup message declaring  error in the opening of my css file ...how can i fix it , does anyone have an idea .. thanks
