### ISSUE TITLE
Default `closeBrackets` preference to true

### ISSUE THREAD

**Issue by le717** [adobe/brackets#11078]
Every now and then we get bug reports about quotes, parentheses, and the like not auto-closing. This is because the [`closeBrackets`](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#list-of-supported-preferences) preference is defaulted to `false`. I would actually expect this to be on by default, as it is rather expected behavior by any modern IDE/code editor. Since preference work is being done in 1.4, this would be an opportune time to make the change.

/cc @ryanstewart

**Comment by redmunds** [comment]
IIRC, `closeBrackets` was not enabled by default because "type through" was not supported well enough.

**Comment by abose** [comment]
What is `type through` ?

**Comment by redmunds** [comment]
Here's an example:
1. Turn on *Edit > Auto Close Braces* and open a .js file
2. Type `alert("x`
3. Notice that the closing paren and double-quote were inserted so text is `alert("x")`
4. Now type `")`

Result
Resulting text is `alert("x")`. Brackets recognized that it had automatically inserted `")` so it did not insert those chars again when you typed them. That's "type through". This is helpful to people who type fast and don't realize that (or care to change their typing habits for) editor that is auto-closing braces, quotes, etc.

As you can see some type through is supported. Maybe CodeMirror has improved this feature since it was first enabled in Brackets. We need to decide which type through cases are required and make sure they are supported.

cc @peterflynn

**Comment by abose** [comment]
raised #11688 with default autoclose. I tested with js and json files and works pretty well now. I think this is goo to be set by default.

**Comment by abose** [comment]
This feature is very handy and i never knew this existed in brackets :sweat_smile: .The PR has been merged. Closing This issue.
Any problem arising due to this could be raised as other issues :)
