### ISSUE TITLE
Please add option to disabe font-smoothing

### ISSUE THREAD

**Issue by SeaofThought** [adobe/brackets#11085]
I can't find a way to disable font-smoothing in Brackets. I'm using Windows 7 with anti-aliasing disabled and it works great with Sublime, Eclipse, etc, where I use Courier New or some similar font. I have 100% vision and a 92dpi monitor, so my experience with smooth (blurred) fonts is exactly as described here:

"There are those who get visual fatigue, headache and sore eyes from reading blurred fonts. There are those who want their eyesight to stay good for as long as possible. There are those who dislike, or even hate smooth font rendering. Perhaps, it’s all down to personal perception, perhaps they are in the minority, but who has extra time to waste on slower-reading fonts, or an extra pair of eyes to damage?"
http://annystudio.com/misc/anti-aliased-fonts-hurt/

It would be great if you could just add an option to disable font-aliasing. Without this I can't even consider using Brackets for any considerable period of time.

Thank you so much!

**Comment by nethip** [comment]
@SeaofThought  Possibly related https://github.com/adobe/brackets/issues/10398. Could you try launching brackets from command line by passing `--disable-direct-write` as an argument. Please launch `Brackets` from terminal by typing in the following.

`Brackets.exe --disable-direct-write`

**Comment by SeaofThought** [comment]
Many many thanks!! That worked great!!! :) (super-smile)

**Comment by nethip** [comment]
:smile: Glad it worked.

**Comment by thiagocpaim** [comment]
I'm using linux... how can I disable direct-write?

**Comment by denisftw** [comment]
Yeah, it doesn't work on Linux, but even if it did, passing `--disable-direct-write` is not a solution.

Most Linux applications I'm aware of, including Chrome, Atom, Opera etc use font-smoothing settings from a file called `fonts.conf`, which resides at `~/.config/fontconfig/fonts.conf`. On my system, the relevant part is:

```xml
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <match target="font">
  <edit mode="assign" name="antialias">
   <bool>false</bool>
  </edit>
 </match>
</fontconfig>
```

They see that it says `antialias` = `false` and understand that font smoothing must be disabled. 

I suspect, some part of Brackets still uses this setting (maybe the rendering pane), because when I change the editor font to `Courier New`, antialiasing inside the editor disappears. However, by default it's antialiased and the menu font is antialiased no matter what, which is obviously unacceptable.
