### ISSUE TITLE
Move live-dev-profile / make it smaller

### ISSUE THREAD

**Issue by yyyyyake** [adobe/brackets#11165]
Hello!

Im working in a enviorment where my "C:\Users******\AppData\Roaming" folder cant be to big, and the live-dev-profile keeps filling my space up. Is it possible to tell brackets so store this data in another place? If so, how would you go about doing this?

Thanks!
Jakob

**Comment by abose** [comment]
I have not seen brackets taking too much memory (above 50mb) in the roaming folder.
What is the memory limits you are on. Also the use case in which the live dev profile folder has large size?

**Comment by redmunds** [comment]
Try minimizing the cache size for live-dev-profile. You should be able to do this by opening Live Preview, then edit cache settings in that browser window.

Another option is to switch to the new multibrowser live preview using *Enable > Experimental Live Preview*. This will use default browser profile instead of live-dev-profile.

**Comment by abose** [comment]
@redmunds Thanks for the info. I didn't know that.

**Comment by yyyyyake** [comment]
@abose i dont have to much space to work with in the roaming profile, around 10gb's i think. It holds alot of info from different programs so every bite counts.

After 1 day of brackets use my live-dev-profile was 350MB, so it was filling up quite fast. 

But after clearing my chrome history it went down to 75, so that is good. 

I will try @redmunds suggestions during the day.

Thanks for the answers guys!

**Comment by saurabh95** [comment]
Fixed in https://github.com/adobe/brackets-shell/pull/596
