### ISSUE TITLE
UI menu and side bar font unresizeable and tiny

### ISSUE THREAD

**Issue by FriendOfFatBeagle** [adobe/brackets#11161]
Bracket Release 1.3 experimental build 1.3.0-16022 (release cd0a6aae5) 
build timestamp: Mon May 11 2015 02:16:09 GMT-0700

I have the above Bracket version installed in Linux Mint 17.1 Cinnamon and Windows 7.
There is no such problem ( to be explain below ) for Win7,  only in Linux Mint 17.1, Cinnamon "Rebecca".

The installed Brackets has a very tiny GUI menu and side bar fonts (about 5 or 6 points in size) and they are also NOT resizeable.
To get a true feel of the problem, open up LibreOffice and create the following texts at the font size shown:

"Current GUI menu and side bar font sizes at 5 or 6 points in Bracket"         
"Brackets editor font size at 12 point"

Question:  How to set the font size of menu and sidebar texts to say 1o or 12 points font.

Here is the screenshot, but it may not show the actual problem due to an enlarged image to fill the designated image area.
On my laptop, when I clicked on the image below, it opens the image in a new browser tab and gives me an apparently correct font size as seen on Brackets for my problem.  

![screenshot from 2015-05-24 20 53 19](https://cloud.githubusercontent.com/assets/4752711/7791103/8aba34e6-0257-11e5-9e32-b83d39b1f9ac.png)

Note that this is not the same problem as thin fonts.
This is a problem of not able to adjust for a larger UI size fonts. 
Common folks, 5 or 6 points fonts is hard to read unless you are an ant....:-)  IMHO.

**Comment by FriendOfFatBeagle** [comment]
I guess this is closed .....

But here is some  info .....
I  tried Atom editor, and it has similar problem since it is a web/browser technology based editor.
It was solved using this plugin:    https://atom.io/packages/hidpi
It has an explanation on why UI font is not working in Linux like it should in Mac.
Excerpts:
Atom HiDPI / Retina
Atom Hidpi scales Atom's interface based on the current monitor's resolution. Currently on Linux Atom does not scale based on DPI, so this package is necessary to make Atom readable on monitors with high resolutions / DPIs. This package should not be necessary for OSX because it automatically scales. I have not tested Atom on Windows so I do not know how it behaves.

May be someone can look at hidpi plugin code to fix similar problem on Brackets
I did not know enough of Brackets to do any good at the moment.
Please advice.

**Comment by TomMalbran** [comment]
You could try this extension: https://github.com/tobibeer/brackets-custom-css
It basically allows you to define your own css rules to change the Brackets UI, plus it also increases the font size a bit.

Or you can use this other extension: https://github.com/1beb/ui-too-small/blob/master/main.js

**Comment by FriendOfFatBeagle** [comment]
Thanks.
I tried this ;  https://github.com/1beb/ui-too-small 
It gives larger font for menu ui without any change.
But the pop-up windows fonts are really small.
See below, and compare relative size of fonts in white background and popup window (blue background).
The font in white background is normal readable size, while the blue popup window fonts is very tiny.  Any solution?

![screenshot from 2015-06-10 23 59 24](https://cloud.githubusercontent.com/assets/4752711/8100764/1cd38cba-0fcd-11e5-80d3-587ddb501d25.png)

**Comment by TomMalbran** [comment]
You can use the first extension mentioned to define your own styles. Or make an issue in the second one asking to increase the font-size in more places around the ui.

The issue here is that cef (the chromuim used in Brackets-shell) wasn't updated on linux because of some issues found when trying it. The current chromium version used for linux does not support high dpi, so until that is fixed, you need to use an extension to fix this issue.

I am closing this since we are tracking the cef issue here: #11047 which should fix this.

**Comment by scarleo** [comment]
This makes brackets completely useless for me, uninstalling

**Comment by daman99** [comment]
Still not resolved. And it's a Windows issue as well.

**Comment by tjdickinson** [comment]
I have the same issue on Windows 10. Everything is so tiny! Strains my eyes trying to see it.

**Comment by kpeters58** [comment]
Developers really need to be aware of accessibility issues!
There are many, many users who do not have 20/20 vision - age or other issues. @Developer kids: You'll get there, too!

I have the same issue on Windows 10. Everything is so tiny! Strains my eyes trying to see it. Ruining an otherwise brilliant project with awesome outside-of-the-box ideas :(

**Comment by asathoor** [comment]
I have the same issue. I cannot read the sidebar. Perhaps a looking glass would help? Brackets is cool in many ways, but pretty useless if you cannot read the GUI.

If it is a matter of CSS - could a developer please tell the name of a class or id (or whatever tag)  where the sidebar font size is defined?

**Comment by JoshMelton** [comment]
The issue people are having is that they shouldn't have to install a plugin for this setting 3 years after the fact this issue was brought up to them to change a fairly glaring oversight in my opinion. I was looking for a new IDE and thought bracket's looked like it could fill that roll.

**Comment by cybiz** [comment]
Check out 'UI Too Small'

**Comment by satovey** [comment]
The small font size in brackets is not a brackets only issue.

This issue is a long standing, systemic, industry propagated issue that after so many decades of existence, appears will not be taken care of without legislation being passed that makes it illegal for companies and developers to design and distribute a User Interface, whether that User Interface be an Operating System, a program or a website; whether that User Interface be proprietary or open source, whether that User Interface be a fee based program or freely distributed program, that does not include within it's design foundation, a provision that allows the user the ability to increase the font size in settings. And such functionality must not require an upgrade to pro or any other version to have the functionality.

I have my system screen resolution set to 1280x720 in an attempt to deal with these constant and imposed annoyances.

In the Win98 days, I stuck with 800x600 for the simple reason that I did not see a point in increasing the resolution on my monitor that served no other purpose than to make it harder for me to see what is on the screen.

The greater the monitor resolution, the greater the problem. I am of the opinion that this is such a huge problem that websites such as Facebook are now discriminating against people with lower screen resolution. When I click on a Facebook story, I see a black box with a line of text that tells me to increase the width of my browser. When I click the maximize button, I see a black box with a line of text that tells me to increase the size of my browser.

As I said earlier, this issue is not a brackets only issue. It took me a good while to get Notepad++ set to a point where I could read the tabs and the menu bar. The explorer pain is still too small and there is no way to adjust the size of the font. 

I have this problem in both open source programs as well as well as programs I purchased and paid for with good money.

Ultimately, people with visual problems will not be able to use their computers because big tech just does not care about people that do not have 20/20.
