### ISSUE TITLE
Live Preview Not Working

### ISSUE THREAD

**Issue by hnbvt24** [adobe/brackets#11222]
When I go to click Live Preview on Brackets, it opens Chrome and then says:
This webpage is not available

ERR_CONNECTION_REFUSED

Google Chrome's connection attempt to localhost was rejected. The website may be down, or your network may not be properly configured.

I've already tried uninstalling extensions and re-installing Brackets, but nothing works. My guess that is that something is wrong in the Project Settings. I went there once and may have changed the URL, and now it currently is set at going to http://localhost:8000/.

If anyone is able to help me figure out how to fix this, that would be much appreciated. Thank you!

**Comment by redmunds** [comment]
Only use Base URL if you are using your own local server. If so, make sure your server is started, otherwise delete Base URL (i.e. set it to [blank]).

If it's still not working, read the [Live Preview section of the How To Use Brackets doc](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#live-preview) and then the [Live Preview Isn't Working section of the Brackets Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting).

**Comment by hnbvt24** [comment]
Oh wow, haha. I don't know why I didn't think of that. Sometimes, I tend to over think these things. It worked! Thank you so much.

**Comment by MarcelGerber** [comment]
Closing as fixed then.
