### ISSUE TITLE
Feature request: record keystroke macros

### ISSUE THREAD

**Issue by mstrong64** [adobe/brackets#11239]
Very handy when editing multiple lines of repetitive code e.g. from the Delphi IDE http://www.haydenr.com/delphi/codingtips/codingtip23.html

**Comment by TomMalbran** [comment]
Have you tried the multiple cursor? You can get lots of cursor and make all the changes you need on multiple places at the same time.

**Comment by mstrong64** [comment]
Nice, but not the same thing. Another example is TextMate (Edit -> Macros).

A recent example. I had a long list of objects:

{ "desc1", "val1" }
...
{ "descN", "valN" }

I needed to swap the order of the members in each object in the list, to:

{ "val1", "desc1" }
...
{ "valN", "descN" }

When there's lots of items in the list then recording a macro to do that
editing is SO much faster.

Cheers,
Michael

**Comment by TomMalbran** [comment]
I know is not really the same. But this feature might be hard to do, and it might not be added into core anytime soon since I don't that it was requested by many users. So you might need to create an extension or get someone to do it, since I don't think that there is one. So for now multiple cursor can do most of that.

One way of doing that is selecting all of the items in one right side using multiple selections, cuting all of them, and then moving\placing the cursor to right after the `{` and doing a paste.

**Comment by mstrong64** [comment]
Thanks Tomás, but that wouldn't have worked for me in this case. I ended up
using TextMate to do this, but I much prefer using Brackets hence the
feature request. This is more of a nice to have than an urgent request
because I can use other tools to get the job done.

**Comment by TomMalbran** [comment]
This might make a really nice extension. Maybe someone would like to do one.

**Comment by redmunds** [comment]
Someone on the forum was working on a Macro extension. See [this thread](https://groups.google.com/forum/?fromgroups#!topic/brackets-dev/y5lu-1rs0pg).

Marking this as an Extension Idea.
