### ISSUE TITLE
Is it possible to change tab size from 4 spaces to 2 spaces?

### ISSUE THREAD

**Issue by SuperManEver** [adobe/brackets#11251]
I'd like to change TAB width from 4 spaces to 2 spaces. Is it possible?

**Comment by rroshan1** [comment]
Yes. It is possible!
The bottom right corner in Brackets provides you an option to define the Tab behaviour along with the width. (spaces/tab size: \<characters width\>). So, for your requirement you just need to keep spaces and change the width to 2 characters.
Closing the issue for now. Please feel free to get back here if your issue is not resolved.

**Comment by SuperManEver** [comment]
Oh my gosh, it so simple :-)
