### ISSUE TITLE
Code folding problem with some theme.

### ISSUE THREAD

**Issue by zolock** [adobe/brackets#11324]
I'm using windows 8.1 64bit, and when I download some theme, there is a "bug" with the code folding part.
![problem](https://cloud.githubusercontent.com/assets/7304650/8409266/abe1d40e-1e76-11e5-9575-ada7f3dce5c2.jpg)

I mean the cross instead of triangle.

**Comment by thehogfather** [comment]
@zolock the default marker is a triangle - but this can be overridden by themes. The theme shown in the image has chosen to render the fold marks as a `+`.  Since it is not a core brackets issue, you can file an issue with the author of the theme you are using. Please clarify if I have misunderstood the issue.
