### ISSUE TITLE
French: String "Marked for disabling" appears unlocalized

### ISSUE THREAD

**Issue by Tania-Jiacomini** [adobe/brackets#11461]
EN: Marked for disabling
FR: Marqué pour désactivation

String is correct in TM export provided, not implemented in build.

![eng-18](https://cloud.githubusercontent.com/assets/2284774/8851500/1d1c0cde-3150-11e5-8dd4-f8ffd48cb179.png)

![fr-18](https://cloud.githubusercontent.com/assets/2284774/8851505/22cff988-3150-11e5-904b-ae0a0931dd8c.png)

**Comment by abose** [comment]
Fr is part of adobe maintained translations. 
@rawat11 Please look into this.

**Comment by rawat11** [comment]
@abose This string is not externalized possibly because this string is not externalized.
We have a string with us for whiich we have japanese and french translated but you might be using the other string. cAn you please once check and let us know.

The one string which received was "Marked for disabling" with String Id MARKED_FOR_DISABLING

**Comment by nethip** [comment]
This is fixed now.
