### ISSUE TITLE
Strip <tags></tags> where the cursor is

### ISSUE THREAD

**Issue by fr32c** [adobe/brackets#11489]
As I mentioned here: https://twitter.com/fr32c/status/625519766611083264
I am looking for an extension to get a shortcut for something frequent in my cleaning code work : *manually* removing useless span tags. (Manually because some of the tags are useful…)

This extension, with the desired keyboard shortcut, would strip tags where the cursor is:
If my text looks like this:
`<h1>my <span>bld</span|> txt</h1>`
(I put a fake Cursor/pipe in closing span tag)

Then pressing the shortcut would result in this:
`<h1>my bld txt</h1>`

To give you a more real world example, I'm regularly using the html/epub export from inDesign, and the result can be:
`<h1 class="myClass myOtherClass">mytext <span class="ThisIsMyParagraphStyle- _idGenCharOverride-1">(AnotherText</span><span class="ThisIsMyParagraphStyle- _idGenCharOverride-1">)</span></h1>`
Expected text, with just 2 clicks and 2 times the shortcut:
`<h1 class="myClass myOtherClass">mytext (AnotherText)</h1>`

By the way, this selection already exists, since Brackets is highlighting the whole span set when I'm placing the cursor there, i'd love to remove evrything that's "green" (if this can help).

**Comment by MarcelGerber** [comment]
Closing this issue as that's our normal process for extension ideas. Developers looking for an idea will still be able to find it.

**Comment by qtbeee** [comment]
Hi, just wanted to say I just published an extension for this called Tag Deletion.

**Comment by hass0302** [comment]
@qtbeee Hey, I just wanted to say i am using your tag deletion extension and its been great. I am wondering if you can improve it by adding the following features. if possible.

let say the line text is as follows "<p><strong>title</strong></p>"
i am wondering if you can do it so that it still select the same line after first deletion because sometimes i just want the "title" and not the p and strong tags.

also if you can do that for multiple cursor selections that would be wonderful.

Cheers, keep up the great work.

**Comment by qtbeee** [comment]
@hass0302 
I've updated the extension to work for multiple cursor selections. Let me know if you find any problems. I'm planning on making it so the selections stay selected over the weekend.
