### ISSUE TITLE
brackets DevTools

### ISSUE THREAD

**Issue by THPUG** [adobe/brackets#11536]
Hi All,

When using brackets Development Tools, console.log and all other messages are shown the wrong file and code line numbers.

e.g.if I ran test.js with console.log('test') in line #5 - the DevTool will display it but from a different file and line number: '/LiveDevelopment/Agents/ConsoleAgent.js:55'

this make it harder for troubleshoot and monitoring code flow.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/3125920/9038770/946138de-39ff-11e5-9895-179eb6e4d033.png)

Thanks,
Nevo.

**Comment by MarcelGerber** [comment]
That's a limitation we can't avoid. Notice that the Brackets Dev Tools don't have much to do with your actual Live Preview session - they will show you your webpage's console messages, but otherwise, everything you do in there (e.g. execute a command) happens within Brackets and not on your webpage.
Notice though that it still gives you file and line of a console message.

Assuming you have `File > Enable experimental Live Preview` ticked, you can even use the browser's Dev Tools for a much nicer debugging experience.

**Comment by THPUG** [comment]
Thank you for the quick answer, The experimental Live preview is not working with PHP server files only with simple HTML, so it is not possible to benefit from it.

Thanks again!
