### ISSUE TITLE
Concern about Network Usage

### ISSUE THREAD

**Issue by ElegantScripting** [adobe/brackets#11663]
I don't use live preview, and I don't look for plugins anymore on Brackets. So in theory, brackets shouldn't be accessing the network.

However, this morning while on my mobile hotspot I couldn't load any websites from my Mac. I had maximum bars on my phone, so websites should have been loading quickly.

I opened my Activity Monitoring application to see why the internet was going so slowly.

And I found this:
![screen shot 2015-09-05 at 10 52 02 am](https://cloud.githubusercontent.com/assets/5307412/9699797/ca03b7e2-53bc-11e5-8d2c-5fd1310082ba.png)

What's Adobe's explanation for this? Why is my network being used so extensively when it doesn't need to be?

It looks like it's just local... but it's having a big effect on my mobile hotspot. Are live previews always active, and being communicated from Brackets to Brackets-Node?

**Comment by abose** [comment]
As the sent bytes and received bytes between brackets and brackets node matches exactly, it is just the local com between brackets and brackets node. The traffic will not reach the WiFi router and will mostly be dealt with at the loopback interface. aka- brackets is not consuming any `internet` bandwidth. Brackets use brackets node for many purposes. If you have installed git extension, it will use node. If you use find-replace that also goes through node. You can go to `debug>show developer tools> network tab` to see what coms brackets does over the network.
The communications between brackets and brackets node in all probability will not go through the hotspot. So something else may be the problem here.
Please switch off the hotspot and see if it is an internet connection problem in the mobile device.

**Comment by abose** [comment]
Closing inactive thread. Please feel free to reopen if you still face the issue.
