### ISSUE TITLE
Windows 10: Cannot open multiple instances from task bar

### ISSUE THREAD

**Issue by sclarke500** [adobe/brackets#11672]
In Windows 8 I could right-click on the Brackets icon in the task bar, and selecting Brackets opened a new instance. 

Repeating those steps in Windows 10 sets focus to the current (already open) instance.

Debug --> New Window works for a work-around.

**Comment by abose** [comment]
@nethip I remeber this as an intentional change for 1.4?

**Comment by petetnt** [comment]
@abose it's intentional, but it's clearly frustrating to many (this is like the tenth issue on GitHub alone asking about the same issue/missing feature after 1.4. was released).

I have an issue #11504 tracking for a better Windows taskbar integration.

**Comment by abose** [comment]
@nethip I rember the check being placed in the case when, if you `open (with)` a file with brackets from explorer, it used to open in a different brackets window. So could we disable the ckeck in case we do not have any file command line args (as is the case with shift click) - that might be the best of both worlds.

**Comment by nethip** [comment]
@petetnt @abose I think for now let us revert the changes which I had done and bring back the old behavior and then we could think about solving other issues (which were fixed with the change but are not that serious compared to this one) while tacking this card (https://trello.com/c/YM0YySxX/679-multiple-separate-windows-official-new-window-command). I will raise a PR for this. Thanks!

**Comment by petetnt** [comment]
@nethip :+1:

**Comment by nethip** [comment]
Raised this PR https://github.com/adobe/brackets-shell/pull/534. @abose Please review this.
