### ISSUE TITLE
Brackets crashes after reloading

### ISSUE THREAD

**Issue by ingorichter** [adobe/brackets#11702]
I've experienced this on Windows 8.1 with Brackets 1.4. I have no extensions installed. Reloading Brackets will usually crash after the first reload and sometimes this will happen after the second reload.

**Comment by petetnt** [comment]
This was fixed in #11505.

I think that this particular bugfix should have been pushed as a version PATCH (as in 1.4.1.) instead of waiting for version 1.5. At worst this bug might have affected **every** Brackets user out there due to it's frequency plus it was a hard crash which makes it even worse. Luckily it doesn't cause data loss.

Brackets hasn't had a patch version yet, but it certainly something that should be looked into in cases like this.

**Comment by abose** [comment]
Closing as fixed. 
release 1.5 will be end of this month mostly. 
tagging @nethip patch release?
