### ISSUE TITLE
open a normal UTF-8 file failed !  

### ISSUE THREAD

**Issue by qcjackman** [adobe/brackets#11730]
I think this is a bug

**Comment by abose** [comment]
It should be a file spesific problem. 
could you go to `debug>show developer tools` and copy the console logs here?
Also, Could you attach a sample file that failed to open in brackets?

**Comment by qcjackman** [comment]
![image](https://cloud.githubusercontent.com/assets/12554120/10039310/4935eefa-6203-11e5-801f-9d1e88dc13dc.png)
I can open it with notepad++ , and Its encoding is indeed utf8 , but when I open with brackets it warning this message

**Comment by qcjackman** [comment]
![image](https://cloud.githubusercontent.com/assets/12554120/10039430/809b2c42-6204-11e5-8d02-f8d302cadf8a.png)
you can see this

**Comment by abose** [comment]
Brackets only support utf8 encoding. We can only investigate something if we have a sample file that causes the problem. You could strip out the sensitive parts of the file and give a minimal file with the problem in brackets and attach it here for us to take a look.

**Comment by petetnt** [comment]
Maybe related to that one weird issue from while back where near empty json file didn't open without BOM. On mobile right now, Ill dig out the issue soon

**Comment by qcjackman** [comment]
I found my file there is a garbled which can not be used to open brackets, maybe brackets will be better as soon as possible to support GBK

**Comment by mseiler025** [comment]
I am using Brackets 1.5 for Windows 10 and getting this error for files that have only 1 character (spaces don't count) followed by one or more new lines.  It makes no difference whether the character is preceded by one or more newlines or not.  If there is more than one character then its working ok.  If there only one character and not a following newline then its working ok.

I've tried this with the characters 'a' and 'b', I have not tested other characters.

**Comment by BobbyBabes** [comment]
Same issue here. With Bracket's own Getting Started index.html file.
This happens on a fresh installation of Manjaro Minimal Net Edition (16.08) with the Linux kernel updated from 4.4 to 4.8.5. And then a medium sized installation of KDE (plasma group package; not the mammoth plasma-meta meta package).
This Google Chrome package was then installed (with pacman) from here : https://aur.archlinux.org/packages/google-chrome/
This Brackets package was then installed (with pacman) from here : https://aur.archlinux.org/packages/brackets/

As usual with these issues, other editors open the file without a hitch and recognise it as UTF-8 showing it in their status bar.

I also attempted to open the index.html file as a separate file (not as part of the default Getting Started folder open at first startup). But I got the same result.
The Getting Started main.css file opens OK.

I already removed the Brackets and Chrome packages, then reinstalled them. With the same result.

Here are some screenshots of the issue.

With the issue in the English language version (root folder):

![brackets-index html-error_20161109_193330]
(https://cloud.githubusercontent.com/assets/22870070/20153057/485bafa2-a6c1-11e6-856b-3f91bdbe7971.png)

With the issue in the Dutch language folder (nl folder). I also tried other language folders with the same issue as a result.:

![brackets-index html-error2_20161109_193330](https://cloud.githubusercontent.com/assets/22870070/20153145/a424ad70-a6c1-11e6-89ca-9377aecf1293.png)

The exact same Getting Started folder (English, root folder) opens without any problems in Atom and index.html is marked as UTF-8 in the status bar :

![brackets-index html-error3_20161109_193330](https://cloud.githubusercontent.com/assets/22870070/20153212/f7584e84-a6c1-11e6-9153-8e65edd95e15.png)

The exact same Getting Started folder (English, root folder) opens without any problems in Sublime Text and index.html is marked as UTF-8 in the status bar :

![brackets-index html-error4_20161109_193330](https://cloud.githubusercontent.com/assets/22870070/20153246/215ec294-a6c2-11e6-886f-844b4ecfbd32.png)

**Comment by BobbyBabes** [comment]
OK, I fixed the issue. But it happened accidentally, as a positive side effect of another issue.
When I installed KDE, a non-existent locale was created : "en_NL.UTF-8".
This caused an irritating message after using the man command : "man: can't set the locale; make sure $LC_* and $LANG are correct".
I found this fix : https://github.com/PanderMusubi/locale-en-nl
After installing this fix for the locale issue, the issue with Brackets was also fixed.
I know this for a fact because I fired up Brackets prior to installing the locale fix, and was still shown the error popup. And I fired up Brackets right after I had installed the locale fix.
Then I updated Brackets from v1.7 to v1.8 and it's still OK.

en_NL.UTF-8 error:

![en_nl-locale_20161115_143845](https://cloud.githubusercontent.com/assets/22870070/20308289/786db434-ab43-11e6-9363-890453379e37.png)

en_NL.UTF-8 error fixed:

![en_nl-locale-fixed_20161115_144035](https://cloud.githubusercontent.com/assets/22870070/20308360/cbd3823e-ab43-11e6-8c2b-c8319a1a1550.png)


Brackets fixed (after installing the locale fix):

![en_nl-locale-brackets-fixed_20161115_145223](https://cloud.githubusercontent.com/assets/22870070/20308311/9414cb32-ab43-11e6-8c57-944b41d91dbe.png)
