### ISSUE TITLE
Built-in nodejs version

### ISSUE THREAD

**Issue by oscarotero** [adobe/brackets#11748]
Hello.
Currently brackets has a built-in nodejs version 0.10.x. Any plans to update to node 4?

**Comment by Denisov21** [comment]
Hi @oscarotero 
Yes, of course. Working in progress in prevision of Brackets 1.6

**Comment by oscarotero** [comment]
Great news!!
patiently waiting for that version
thanks!

**Comment by abose** [comment]
You can track the change here. https://github.com/adobe/brackets/pull/11674

**Comment by oscarotero** [comment]
Thanks, @abose . I had seen this issue but thought it meant to simply add node 4 to travis config file, not to update the built-in node.
I'm subscribed

**Comment by dmikrot** [comment]
This is blocking my attempt to write a [stylelint extension](https://github.com/dmikrot/brackets-stylelint), since [stylelint does not support Node 0.10](https://github.com/stylelint/stylelint/issues/201).

Note that stylelint has [plugins](http://stylelint.io/user-guide/complementary-tools/) for Atom, Sublime Text, and Visual Studio Code, but not Brackets.

**Comment by zaggino** [comment]
@dmikrot almost there https://github.com/adobe/brackets-shell/pull/543
