### ISSUE TITLE
Old Window Design on El Capitan with New Window

### ISSUE THREAD

**Issue by juice** [adobe/brackets#11827]
If you open a New Brackets Window via the Debug Menu, the old OS X Window Design shows up.

<img width="159" alt="screen shot 2015-10-15 at 18 31 10" src="https://cloud.githubusercontent.com/assets/179705/10520551/f44e6dda-736a-11e5-8c86-25d8b9fa6b1d.PNG">

**Comment by petetnt** [comment]
This has been fixed in 1.5. which is out very soon :fire_engine:

**Comment by juice** [comment]
1.5 is out. This happens on 1.5. As i wrote, it happens if you open a New Brackets Window via the Debug Menu.

**Comment by petetnt** [comment]
Oh, dang. My bad!

**Comment by nethip** [comment]
@juice Thanks for reporting this. This indeed is a bug. This got missed in 1.5.

 I had fixed this with the main window but looks like the same fix needs to be applied to the new debug window workflow  :disappointed: Please expect this to get fixed in the next release. If this is affecting your workflow, let me know and I can provide you a build with the fix. Sorry for the inconvenience.

**Comment by nethip** [comment]
I have raised a PR for this https://github.com/adobe/brackets-shell/pull/539. @abose Most of the code is taken straight from the Brackets window workflow. Please review it, and if it looks fine go ahead with the merge.

**Comment by abose** [comment]
Merged. Closing. This will be fixed in 1.6.
