### ISSUE TITLE
Can't Update to 1.5 

### ISSUE THREAD

**Issue by AlexandreBT** [adobe/brackets#11831]
Hi,

Early today, i wanted to update on version 1.5 but during the upgrade,I got an error message. "Access denied for the folder C:\Programs Files\Brackets.

I'm on Windows 10, I've only one account, me: administrator. Brackets don't appears in my programs, the only thing i've found is the Brackets folder in Program Fils, but ... Access denied.

I tried many things but, I can't install / update Brackets. Sorry for my English. 

When I click on the folder => http://i.imgur.com/iIrsZiq.png
When I want install / upgrade => http://i.imgur.com/ilajj1y.png

Thanks

**Comment by abose** [comment]
It looks like some permission issue. Make sure that you have sufficient permission to install `C:\Program Files (x86)\Brackets` .  Or restarting™ before installing might fix it.

**Comment by abose** [comment]
Closing inactive thread.

**Comment by leadbooster** [comment]
Same problem here. I was in edition of something when I was ask to upgrade and then offered to restart, so installation can go.  Brackets is the only folder I can't access in `C:\Program Files (x86)\`.  Maybe because, it is still in installation cancellation (extremely long). I will try to reinstall asap and if this fail, I'll restart my win10 before retry.
