### ISSUE TITLE
Cannot search for tags?

### ISSUE THREAD

**Issue by ArneAnka** [adobe/brackets#11857]
Hi!

Searching for some tags docent work. Cannot find anything in the help about this subject either. Bug?

<img width="634" alt="brackets" src="https://cloud.githubusercontent.com/assets/5988810/10715541/32bfbc52-7b1a-11e5-872e-35714305e5c8.png">

**Comment by petetnt** [comment]
You have RegExp-mode on (the `.*`-button after `aA`-button). `?` as a special meaning in RegExp, which makes your search equivalent of having `<` between zero and one time, as many times as possible, giving back as needed followed by literal `=` (see it on RegExp101: https://regex101.com/r/nQ5lO3/1).

You can either turn the RegExp-mode off, or change your query to `<\?=` so that the `?` is being used as a literal match instead of quantifier.

**Comment by abose** [comment]
Click the `.*` button to disable regex search mode. That should fix the issue.

**Comment by abose** [comment]
Closing inactive thread.
