### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by dhanyn10** [adobe/brackets#11851]
options syntax highlighter when the document ddn't save yet, same like notepad++ or sublime text

**Comment by dhanyn10** [comment]
![syntaxhighlight](https://cloud.githubusercontent.com/assets/11478316/10695803/dcf6ed36-79cf-11e5-9a49-2c5925438369.png)

**Comment by petetnt** [comment]
You can change the syntax highlighting mode by clicking the dropdown menu icon in the bottom (by default it says `Text`

![image](https://cloud.githubusercontent.com/assets/7641760/10702403/2a292f68-79d2-11e5-9789-a9290acad90a.png)

**Comment by abose** [comment]
Feature already available. Closing.

**Comment by ficristo** [comment]
@abose If you create a new file without saving it you can't change the syntax highlight.
I think @dhanyn10 meant that.
This should be reopened (I think there is already a similar issue).

**Comment by petetnt** [comment]
@ficristo I remember that issue too, couldn't find it (it was about new files having a other default than Text, right?). However, the current syntax highlighting currently works as same as Notepad++ mentioned in the OP - mode being changed after file was saved, but it can be changed without file being saved too (manually).

If this issue is about having an other default than `Text`, then this can be reopened or continued in the old issue (if I could find it, that is... :ghost: )

**Comment by ficristo** [comment]
@petetnt I think I saw a different issue.
The point here is it should be possible to change syntax highlighting **without** saving the file.
Sometimes you want to copy a piece of code from somewhere else in a new file in Brackets, then syntax hightlighting it, have the ability to code collapse and so on without saving the file because you do not need the file but only the content.

If it is already possible to change the language how can you do?
To me seems possible only after I save the file.
![syntaxhighlight](https://cloud.githubusercontent.com/assets/10583268/10710793/d2a30600-7a68-11e5-9344-2698ec714e43.png)


PS: @dhanyn10 let me know if I totally misunderstood your issue.

**Comment by abose** [comment]
We're tracking the work needed to enable that dropdown on our feature backlog, here: [Fix JS Code Hints problems with untitled documents (enable language switcher)](https://trello.com/c/CNXuU4TY/1369-fix-js-code-hints-for-untitled-documents-enable-language-switcher).  Please upvote that item to help raise its priority.

duplicate #9409

**Comment by dhanyn10** [comment]
ok, it same with the issue #9409

**Comment by RYJASM** [comment]
Well it has been a few months and there's been new releases. This still isn't fixed or added. Any updates?

**Comment by danschalow** [comment]
Still no progress on this one? Albeit it small, it's a real niggly one.
