### ISSUE TITLE
Variable Default Save Location

### ISSUE THREAD

**Issue by Alexkun77** [adobe/brackets#11853]
when i save a file, in file browser it opens the following location opt/brackets/samples/root/Getting Started. I want to change this location to something else so that i don't have to navigate back and forth again and again.

**Comment by rroshan1** [comment]
@Alexkun77 Brackets always has an active project ("Getting Started" project by default).
Whenever you edit a new file and try to save it, it starts with the project root as default save location.
<b>Workaround:</b>
You can point to the folder where you want to save the files as the active project.

You could also upvote the feature request- support for closing the active project in Trello so that we could pick it up later on priority. https://trello.com/c/RFi7TFyj/412-brackets-should-support-having-no-active-project.
Closing the issue for now.
