### ISSUE TITLE
File display become hidden with fenced code `diff` in markdown file GFM

### ISSUE THREAD

**Issue by ldez** [adobe/brackets#11947]
## Description

Use GFM style by default for Markdown file.

### Case 1

- Create a file `test.md`
- Copy/paste :
```markdown

```diff
foo
bar
foo
bar
```\
```

The file content become hidden.

### Case 2

- Other way, just create a file `test.md` and try to write a fenced code with `diff` as language.
   - it fail because Brackets add an extra `f` : result `difff` not `diff`

## Informations

Brackets version : Version 1.5 - 1.5.0-16538 (release cf9cf4698) 

- Ubuntu 15.04, 15.10
- Windows 7 64bits

Reload Without Extensions : reproduce the bug

Console output :

```
Uncaught TypeError: Object #<Object> has no method 'startState' markdown.js:19
```

**Comment by ficristo** [comment]
The first case is this https://github.com/codemirror/CodeMirror/pull/3994. I tried locally the fix for the markdown and worked.
The fix doesn't seem in a release of CodeMirror yet. So it will require a CodeMirror update or we could cherry pick the fix.
@MarcelGerber @MiguelCastillo what do you think?

I don't understand the second case...

**Comment by ficristo** [comment]
Cannot reproduce anymore on 1.7
If you have still problem reopen or open a new issue.
