### ISSUE TITLE
Live Preview error

### ISSUE THREAD

**Issue by skbelalmd** [adobe/brackets#11968]
Is there any method, so that the live preview will open in a particular port.
i.e. After making change in file=>Project Setting,
I have set a specific port like http://127.0.0.1:55708.
But while connecting to live preview it gives error.

**Comment by redmunds** [comment]
I haven't tried this, but it looks like the `StaticServer` code [checks for a "port" Preference](https://github.com/adobe/brackets/blob/master/src/extensions/default/StaticServer/StaticServer.js#L137), so try adding a Preference something like this:

```json
    "port": 55708
```

**Comment by skbelalmd** [comment]
Yes, It is done.

In the brackets preferences file changed the static server port to a value and now every time brackets open with that specified port.


Thanks Dude


________________________________

**Comment by redmunds** [comment]
Thanks for confirming. I was checking to see if the [list of supported preferences](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#list-of-supported-preferences) was up-to-date, and it lists this preference as `staticserver.port` instead of simply `port`. Can you try both and let me know which ones work or not so I can update the documentation? Thanks in advance.

**Comment by piga** [comment]
I typed something wrong in Project Settings and than Live Preview stoped working. Than I was playing with "staticserver.port" but I didn't solve the problem. Than I erased all from Project Settings and everything was OK again.
