### ISSUE TITLE
quick edit doesnt work for custom modules under node_modules

### ISSUE THREAD

**Issue by NikosEfthias** [adobe/brackets#12088]
quick edit doesnt work for custom modules under node_modules but works for modules those were installed through npm

**Comment by ficristo** [comment]
@NikosEfthias what do you mean exactly with _custom modules_?

**Comment by NikosEfthias** [comment]
i meant the modules i wrote and linked under node_modules

**Comment by ficristo** [comment]
Are you using `npm link`?

**Comment by NikosEfthias** [comment]
nope internally i have a gulp task linking all custom modules using ln -s

**Comment by redmunds** [comment]
@NikosEfthias The info generated by the JavaScriptCodeHint engine is the same info used by the Jump command to open the correct file. Search on DEFAULT_EXCLUDED_DIRECTORIES (in extensions/default/JavaScriptCodeHInts) and you'll see that the node_modules folder is excluded by default because it's generally very large and a big impact on performance. Try removing that and see how it works for you.

Also read through the [JS Code Hints wiki page](https://github.com/adobe/brackets/wiki/JavaScript-Code-Hints) for more info about further configuration options.

**Comment by NikosEfthias** [comment]
yes it does the trick though as you tell it effects the performance awfully so seems i need another solution
