### ISSUE TITLE
Can't install on latest Ubuntu 15.10 64bit [v1.5 and v1.6]

### ISSUE THREAD

**Issue by dvorapa** [adobe/brackets#12149]
I can not install v1.5 and v1.6 of Brackets because of a problem with dependency, which couldn't be met

**Comment by dvorapa** [comment]
Connected with https://github.com/adobe/brackets-shell/pull/501

**Comment by petetnt** [comment]
https://github.com/adobe/brackets/issues/10255 contains workarounds and builds with the dep included

**Comment by dvorapa** [comment]
I've found it before, but thanks. I thought it will be fixed in v1.6, but still isn't :cry:

**Comment by abose** [comment]
Closing as this issue is already tracked.
@dvorapa We did not get a clearance from adobe legal to ship the libgcrypt dependancy alongside brackets. This is due to licensing issues with distributing libgcrypt which is under GPL license and MIT license under which brackets is distributed is incompatible.  The linux GNU guys can land brackets in hot legal waters if we were to distribute libgcrypt.
