### ISSUE TITLE
memory leaks realted to MainViewManager currentFileChange

### ISSUE THREAD

**Issue by joseporto** [adobe/brackets#12283]
I've been finding several potencial memory leak console.errors regarding the use of **currentFileChange**.

I've tracked them to several extensions that I'm using, and I'm glad to contribute to changing them according to best practices.

Can anyone shine a light on why currentFileChange generates memory leaks, and if there is a better way to use it.

examples for a current implementation, all of these are generating potential memory leaks, according to brackets:

```javascript
MainViewManager.on("currentFileChange", this.onCurrentDocumentChange.bind(this));
```

```javascript
MainViewManager.on("currentFileChange", function() {
        var editor  = EditorManager.getCurrentFullEditor(),
            cm      = editor ? editor._codeMirror : null;
        
        // Update CodeMirror overlay if editor is available
        if (cm) {
            cm.removeOverlay(indentGuidesOverlay);
            if (enabled) {
                cm.addOverlay(indentGuidesOverlay);
                updateStyleRules();
            }
            cm.refresh();
        }
        
        // Update menu
        CommandManager.get(COMMAND_ID).setChecked(enabled);
    });
```

**Comment by ficristo** [comment]
@MarcelGerber can you answer this?

**Comment by MarcelGerber** [comment]
The message you are referring to is `Possible memory leak: 16 'currentFileChange' listeners attached to Object`, as defined in https://github.com/adobe/brackets/blob/86c037f097d475d0e54faf50a998350ece3fe2ca/src/utils/EventDispatcher.js#L119-L122.
Mind the "possible", though. This safeguard is in place so one can spot memory leaks more easily, but not everything it outputs is actually a memory leak.

So, would this number increase every time you, e.g., change documents, this would actually be a memory leak. But as it is, with an one-time installation of the handlers on a non-changing object (MainViewManager instead of the current document), this is not a memory leak, and you can disregard the message.

Closing. (Feel free to chime in if you have any questions left unanswered)
