### ISSUE TITLE
autocomplete for absolute/relative paths

### ISSUE THREAD

**Issue by daggerok** [adobe/brackets#12318]
hello, 

will brackets support relative filename paths (like AutoFileName for Sublime Text, or autocomplete-paths for atom)?

**Comment by redmunds** [comment]
@daggerok Brackets already has this in the UrlCodeHints default extension. It should work in HTML for `href` and `src` attributes and in CSS inside the `url()` function. Is there another case that you would like?

**Comment by daggerok** [comment]
@redmunds, thanks for reply

yes, it is. On my mind two cases at the moment:

1. file system operations, like

```js
app.use(app.static(`${__dirname}/../public`)
```
or
```coffee
response.pipe fs.createWriteStream dstFile
```
2. ability to import/require whatever modules/namespaces i need using TypeScript/ES6/CommonsJS

```js
/// <reference path="../../typings/tsd.d.ts" />
import Models from '../../src/modules/Models'
import chai = require("chai")
const nock = require('nock')
```

It can be different file extensions, so I must be able to configure it somehow for any scripts: js/coffee/es6/jsx/ts

best regards
/Max

**Comment by redmunds** [comment]
It's not currently supported in JS, but it shouldn't be too hard to add the UrlCodeHints default extension. The hardest part may be to integrate it with the existing JavaScriptCodeHints extension. If anyone wants to take this on, let me know and I can help you get started.

**Comment by daggerok** [comment]
@redmunds, can you show me where I can read about UrlCodeHints exctension configuration?

**Comment by redmunds** [comment]
No worries. I already had written some notes up about this, so here they are in case anyone is interested:

- - - - -

Code for UrlCodeHints extension is in src/extensions/default/UrlCodeHints folder.

Code Hints API requires implementing 3 methods:
1. `hasHints()`
2. `getHints()`
3. `insertHint()`

You'll see that main.js already has those 3 methods, but only handles modes for html & css, so you need to add a condition for JavaScript in all 3.

There are probably quite a few cases to handle, so I think it may be best to use a list of regex patterns. If you look in the data.json file you'll see a list of html attributes. This makes it easy to add new html attributes to the list. You might consider listing the regex patterns in that file in a similar way.

The other part to the Code HInts API is that you have to register to provide hints with a priority. This extension registers with priority 5 (higher number gets precedence). You'll need to add "JavaScript" to this list:

  `CodeHintManager.registerHintProvider(urlHints, ["css", "html", "less", "scss"], 5);`

The JavaScriptCodeHints extension uses priority 0, so UrlCodeHints will get precedence. This means that `UrlCodeHints.hasHints()` gets called first. It should only return true if one of the regex patterns gets a hit, and false otherwise so that `JavaScriptCodeHints.hasHints()` is called for other cases.

Also note that collecting the list of files and folders to display in code hints is asynchronous, so deferred objects are used. You should be able to re-use the existing `_getUrlHints()` method for that part.

**Comment by daggerok** [comment]
thank you
