### ISSUE TITLE
problem with install on ubuntu (3rd party and non free)

### ISSUE THREAD

**Issue by mojiremix** [adobe/brackets#12460]
hi i install ubuntu 16 64bit 

i download brackets 64bit.deb

but when double click on .deb file get error and cant install brackets 

open store and

error is : 3rd party and non free 

plz help me

**Comment by lukalazov** [comment]
Had the same problem, I think it is a problem with Ubuntu software. 
//First, open the terminal. and type:

cd Downloads
sudo dpkg -i Brackets.1.6.Extract.64-bit.deb

sudo dpkg -i installs a deb file, and than followed by the deb file name, in my chase it Brackets.1.6.Extract.64-bit.deb, if Bracket is not installing due to missing dependency "libgcrypt11" or what ever dependency, download the dependency install it, and I think it will work, if it doesn't launch, just type in termial:

sudo apt-get install -f 

Hope this helps.

**Comment by mojiremix** [comment]
tanks to help

my problem done 

tanks very much 

I pray to god for u

**Comment by lukalazov** [comment]
Thank you :)

**Comment by mojiremix** [comment]
if anybody cant install this way 
try this

open terminal (with right click in desktop)

and type or paste

sudo apt-add-repository ppa:webupd8team/brackets

after type

sudo apt-get update

sudo apt-get install


after search in dock for brackets and enjoy!



for brackets **extensions** folder

~/.config/brackets/extensions/


enjoy
