### ISSUE TITLE
Can't install/uninstall extensions after upgrade to version 1.7

### ISSUE THREAD

**Issue by Krysisx** [adobe/brackets#12538]
Hi,

I have upgraded to `1.7` from `1.6`, I'm on `Linux Mint 17.3` x64.
I can't install/uninstall (and update) my extensions anymore.
In console I get this error `Unknown installation error extensionManager domain is undefined `.
I tried to reinstall and deleting folder `.config/Brackets` but no luck.
Could you help me?

Thanks

**Comment by drewk3779** [comment]
I am have the same issue using 1.7 I am on Ubuntu 16.04.

**Comment by nethip** [comment]
We have refreshed Linux builds as there was an issue with establishing node connection. Could you download the build again and try installing it?

**Comment by Krysisx** [comment]
Can I use the `.deb` file or do I have to download the source?

**Comment by Gangananda** [comment]
Same problem here, still nothing.

**Comment by nethip** [comment]
@Krysisx Just downloading .`deb` should be fine.

**Comment by nethip** [comment]
@Gangananda Did you try downloading the `.deb` binary again and installing?

**Comment by Gangananda** [comment]
After reinstall all is working fine now. Thank you : )

**Comment by ficristo** [comment]
@Krysisx if you are still having issues after reinstalling please open a new issue.

**Comment by schindld** [comment]
This issue still exists in 1.8. I get the same error popping up and in the console when trying to use the extension manager to install an extension: `Unknown installation error extensionManager domain is undefined`. I **can** install the same extensions manually by unzipping them into the user directory.

The specific version I have installed is 1.8.0-17108 for Windows (x86). I used the msi to install it (https://github.com/adobe/brackets/releases/download/release-1.8/Brackets.Release.1.8.msi). And I think it installed the wrong node architecture. `node -v` from inside the Brackets directory (where node.exe is), gives the following error: 

> This version of node.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

Replacing the node.exe with an appropriate 32-bit one (I had v6.9.2 x86 on hand) fixed the issue, but the brackets msi installer should supply the proper node version and architecture instead of assuming x64.
