### ISSUE TITLE
PHP syntax highlighting isn't very informative

### ISSUE THREAD

**Issue by alexcorvi** [adobe/brackets#12580]
I know that the main focus of Brackets doesn't go toward PHP development, but I can see that this is a necessary feature for a code editor that is getting more and more mature such as Brackets.

**Comment by nethip** [comment]
@alexcorvi Agree with you on adding more PHP relevant features to Brackets. 

Meanwhile, may I recommend Dreamweaver (which just received a complete overhaul of UI and the coding surface by the way), which has great support for PHP. Syntax checking, code hints, device preview, testing server to name few. You could grab a copy of Dreamweaver Beta and play around with it.

**Comment by jburdi** [comment]
This theme does a great job with syntax highlighting for php - https://github.com/cithukyaw/DreamPHP

**Comment by ficristo** [comment]
The syntax highlighting in Brackets come from CodeMirror. I'm quite sure it still miss some keywords.
Apart the keywords can you say more about what you expect?

**Comment by killerog** [comment]
I don't know if it's better to recycle this topic or use a different one. I've been using Brackets a lot for html last weeks and were loving it, but now that I had to mix in some php it started being a bit annoying on the syntax highlighting.
As you can see in the screenshot the closing div isn't recognized anymore because there's a bit of multi-line php in between it (if I remove it the highlighting works fine). Also the outer of the nested rounded brackets aren't recognized as belonging together (pretty ironic for an editor called Brackets ;-)) in the if statement.
Does this help anything?

![brackets-io-snippet](https://cloud.githubusercontent.com/assets/1665411/18872232/ac0579b8-84b9-11e6-8832-31516a5b9016.png)

The actual code snippet:

`                            <div class="row">
                                <php if ( $this->countModules('button-onderdeel-4') ) {
                                        $colWidth = 5;
                                    } else {
                                        $colWidth = 4;
                                    }
                                ?>
                                <div class="col-md-<?php echo($colWidth); ?> product">
                                    <jdoc:include type="module" name="button-onderdeel-1" />
                                </div>
                                <div class="col-md-<?php echo($colWidth); ?> product">
                                    <jdoc:include type="module" name="button-onderdeel-2" />
                                </div>
                                <div class="col-md-<?php echo($colWidth); ?> product">
                                    <jdoc:include type="module" name="button-onderdeel-3" />
                                </div>
                                <div class="col-md-<?php echo($colWidth); ?> product">
                                    <jdoc:include type="module" name="button-onderdeel-4" />
                                </div>
                            </div>
`

**Comment by zaggino** [comment]
@killerog you'll probably want to open an issue with https://github.com/codemirror/CodeMirror
php demo is here: https://codemirror.net/mode/php/index.html and the closing /div error is also present in the demo, Brackets use CodeMirror in the background.

**Comment by ficristo** [comment]
You are missing a `?` inside the first `<php`.

**Comment by killerog** [comment]
Oh man... that's so stupid of me...

It's corner time for me I guess :)
