### ISSUE TITLE
Can't change the project folder in Brackets

### ISSUE THREAD

**Issue by JohnCido** [adobe/brackets#12592]
This occurred several times already and everything turns out fine after several days or so. But this happens from time to time, which really kind of messed up my develop work. I tried to use DeveTool and messages I got listed below:

> Failed to watch root:  /Users/****\* Max connection attempts reached
> /project/ProjectManager.js:751 Error watching project root:  /Users/****\* connection attempts reached
> 
> WebSocket connection to 'ws://localhost:50197/' failed: Error in connection establishment: net::ERR_SOCKS_CONNECTION_FAILED

I also find out that if I launch Brackets and do nothing for some time and it'll have a chance working fine again.
For extensions, I tried to disable them one by one but nothing changes. Seems that it was not caused by any extension installed.

**Comment by busykai** [comment]
@JohnCido, it sounds like something (a firewall, maybe) preventing the editor from connecting to its `node.js` instance. By default on Mac you may check that connections to `Brackets-node` are allowed by going to _System Preferences -> Security and Privacy -> Firewall -> Firewall Options..._. If you're using some other security software, make sure it's configured to allow connections to `Brackets-node`.

Also, make sure connections to `localhost` are no going through a proxy.

It is quite weird, though, that the problem is not permanent and only shows from time to time. Are you switching networks between proxied and non-proxied?

**Comment by ficristo** [comment]
If you still have problems please open a new issue.
