### ISSUE TITLE
No Auto-Complete for JS

### ISSUE THREAD

**Issue by flynnstone9** [adobe/brackets#12698]
Hey just updated to the 1.7 build. Brackets isn't auto-completing for java-script. For example when I use to type "arr" it would fill with "array." 

**It use to.** The auto fill works for html / css still. Is it a setting somewhere that has been adjusted? 

Probably a quick fix. Thanks ahead of time.

**Comment by flynnstone9** [comment]
Just reloaded without extensions and they're working. 

**Is there a method of finding which extension is causing the issue?**

**Comment by ficristo** [comment]
You can look at `Debug \ Show Developer Tools` and see if there is anything.
Otherwise I think you need to disable all the extensions and enable one by one.
The faster way (I don't know how safe it is) is to move all your extensions in the `disabled` folder and then move one by one in the `user` folder again

**Comment by flynnstone9** [comment]
**Hey actually the problem popped up again.** This time when I "Reload without Extensions" it is not working. Any guidance on how to fix this?
