### ISSUE TITLE
Ability to add the authors for each line of code

### ISSUE THREAD

**Issue by 230116885230116885** [adobe/brackets#12711]
Ability to add the authors for each line of code from GIT.

**Comment by petetnt** [comment]
Hi @230116885230116885,

You mean a `git blame` view similar to [the github one](https://github.com/adobe/brackets/blame/master/src/view/ThemeView.js)? 

This is something that an extension (such as the great [brackets-git](https://github.com/zaggino/brackets-git)) should handle instead of Brackets core. I suggest you repost your feature request to `brackets-git` 👍

**Comment by 230116885230116885** [comment]
Yes. Thank you.
https://github.com/zaggino/brackets-git/issues/1310
