### ISSUE TITLE
File tree not working

### ISSUE THREAD

**Issue by DigiSquid** [adobe/brackets#12713]
For some reason the file tree is not working for me on Brackets 1.7 for Mac OS X 10.11.6. It shows a list of files for whatever project was opened last, but I can't really interact with the list. Files and folders can be selected, but they can't be opened. So the only way I have access to my files is through search. Changing projects, or reloading them, doesn't refresh the list either. It's almost as if it's showing me a cached directory or something.

With all that said, I went through the normal troubleshooting procedures of reloading without extensions clearing out my cache and preferences, reinstalling 1.7 and so on but nothing worked. Reverting back to 1.6 does fix the problem however.

**Comment by petetnt** [comment]
Hi @DigiSquid, do you see any errors in the developer tools (`Debug -> Show Developer tools -> Console`)

**Comment by GalawynRM** [comment]
I'm pretty sure is related to Icon^M file on the folder.
I'm currently using an extension to filter out Icon files, waiting for 1.8 fixes

**Comment by petetnt** [comment]
@GalawynRM, this has already been fixed in the master branch (https://github.com/adobe/brackets/pull/12807), not quite sure if it landed to the pre-release but should at least be in 1.8 that should be coming out by the end of the month.

If you want to use the master meanwhile, see the article [How to hack on Brackets](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets) to get started with the Brackets codebase. 👍
