### ISSUE TITLE
Bad head menu, how to fix?

### ISSUE THREAD

**Issue by KhalitovAdel** [adobe/brackets#12848]
Why my menu drop down? How i can fix it?
![2016-10-23 18-49-45](https://cloud.githubusercontent.com/assets/5517534/19627536/120b1dda-995a-11e6-8f40-dcad631fde7c.png)

**Comment by ficristo** [comment]
Can you open `Debug \ Show Developer Tools` and eventually check what there is in the console?

That said usually, especially for Linux users, I advice to use [brackets-electron](https://github.com/zaggino/brackets-electron/) instead of Brackets.
Here https://nathanjplummer.github.io/Brackets/ you can see some known problems, brackets-electron fix most of them.
