### ISSUE TITLE
Update Linux wiki pages with libgcrypt dependency issue

### ISSUE THREAD

**Issue by jacebenson** [adobe/brackets#12877]
### Description

Update Linux wiki pages with libgcrypt dependecy issue for debian variants
https://github.com/adobe/brackets/wiki/Linux-Version

I would have included this change in my pull request but, seems these pages are locked or something.

Please add links to the following work around (haven't tested, but folks have pointed to this) so users can at least try to get it working, or direct them to the Electron based brackets as @ficristo did for issue #10255 

Workaround to be added as provided here;
https://github.com/adobe/brackets/issues/10255#issuecomment-149835747

> debtool: https://github.com/brbsix/debtool
>libgcrypt.so.11: https://tusfiles.net/n2n2hvbqnyfl
>
>Here are the steps:
>
>Unpack Brackets.1.5.Extract.64-bit.deb
>
>debtool -u Brackets.1.5.Extract.64-bit.deb
>Remove the package's dependence on libgcrypt11
>
>sed -i 's/ libgcrypt11 (>= [0-9.]\+),//' ./brackets_1.5.0-16538_amd64/DEBIAN/control
>Copy libgcrypt.so.11 into the package
>
>cp ~/Downloads/libgcrypt.so.11 ./brackets_1.5.0-16538_amd64/opt/brackets/
>Rebuild the package
>
>debtool -b ./brackets_1.5.0-16538_amd64
>Install brackets_1.5.0-16538_amd64.deb
>
>In case it's not clear what is being done, I'm simply removing the dependency on libgcrypt11 and including the library in the package.

**Comment by ficristo** [comment]
In the README file at the root of the repo, there is a guide for known Linux problems: https://nathanjplummer.github.io/Brackets/
Maybe we could add a link in the https://github.com/adobe/brackets/wiki/Linux-Version page too.

**Comment by NathanJPlummer** [comment]
When I proposed the Linux documentation we originally wanted to add it to the wiki. However, the wiki had been locked due to vandalism, which is why it was decided I would maintain the Linux installation page for now and we would put the link in the README.

Honestly the README has a few different areas that mention Linux issues and only one of them provides the link.  One thing I can do is take a look at that and see if there's a way to clean it up so the link is more obvious for someone looking for common Linux installation problems, particularly the libcrypt11 issue.

**Comment by NathanJPlummer** [comment]
@ficristo 

[Updated location to guide in the README](https://github.com/adobe/brackets/pull/12950) and information added to the Wiki by @petetnt so you can close this issue if you'd like.
