### ISSUE TITLE
Lost all saved files when updating from 1.7 to 1.8

### ISSUE THREAD

**Issue by ks927** [adobe/brackets#12912]
Updated from Brackets 1.7 to 1.8 with dozens of files saved. I thought they would transfer over with the update.
They were all gone when I finished installing 1.8. Even tried reinstalling 1.7, but they're still not there.

Please include the OS and what version of the OS you're running.
OS X El Capitan 10.11.6

Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)
1.8

**Comment by swmitra** [comment]
@ks927 Please tell us the following details to know more about the problem.
* Where were these files saved? Did you created all these files in the Brackets default project after the first launch? ( Getting Started )
* Are they not visible from the Brackets project explore only? Are they accessible from OS finder ?

**Comment by ks927** [comment]
Yes they were all saved in the Getting Started folder.

They are both not visible in Brackets and I'm not able to locate them in the OS finder.

**Comment by swmitra** [comment]
@ks927 That explains the problem. "Getting Started" project is hosted from the 'nls/root/Getting Started' which is part of the Brackets install directory. Because of Brackets 1.8 install, when the previous version got uninstalled it removed the contents from the install location then copied 1.8 contents. 

Please make sure to use 'user directory' or some other directory for project work as install directories always have the risk of getting truncated in each install/uninstall.

**Comment by swmitra** [comment]
@ks927 From Brackets perspective in this case we can't really do anything at this point of time. Do let us know whether we can close this issue.

**Comment by ks927** [comment]
you can close this issue

**Comment by swmitra** [comment]
Closing this.
