### ISSUE TITLE
Ext. Installation Failed -Unknown internal error

### ISSUE THREAD

**Issue by TilakMaddy** [adobe/brackets#12953]
Ext. Installation Failed -Unknown internal error during installing an extension called lorem ipsum

**Comment by petetnt** [comment]
Hi @TilakMaddy, 

can you see any errors in the Developer Tools console (Debug -> Show Developer Tools -> Console)? Most likely this is an firewall issue.

**Comment by TilakMaddy** [comment]
I haven;t even opened the browser, i just tried to install extensions using the box button beneath the launch button- after browsing i clicked install and the above is literally the message popup
I am not telling "unknown" thats what the ide is telling.

**Comment by petetnt** [comment]
@TilakMaddy Brackets has it's own set of developer tools (same as those in Chrome) that should show some extra errors along with the "Unknown internal error" message that the UI shows. You should also check the network tab for any additional internet errors.

**Comment by ficristo** [comment]
If you run on a 32 bit Windows platform, you can try this https://github.com/adobe/brackets/issues/12918#issuecomment-261337603
Otherwise, do you mind [running from source](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets) and try this PR: https://github.com/adobe/brackets/pull/12933

**Comment by doige** [comment]
Same problem here. With 1.7 works all fine. With 1.8 (windows 10, office behind firewall) brackets can't install or update any extension.  Proxy ip is in the file brackets.json configured.
I work with 1.7 further.

**Comment by manuel-84** [comment]
same problem on win10 32bit
i also tried to replace node.exe with the x86 official version but this have not fixed the problem

**Comment by nicksoph** [comment]
Same problem on a truly clean, brand new  win10 32bit build - Tried to install of v1.8 as the very first additional program on fully updated Windows 10 laptop. Installed as user: UAC - asks before install, and then proceeds with install with no obvious errors . Errors in Console.log (more info later) Unable to install Extensions - "Unknown Error". Folder permissions check set to 'everyone' having 'full control' on brackets program folder, /user/appdata/roaming/brackets, event log checked and and shows firewall blocked no connections. Uninstalled and installed v1.7, and Extensions can then be installed. Updated 1.7 to 1.8 using autoupdate in Brackets. Still had extensions showing as being installed but still unable to add any new extensions and now attempting uninstalling old extensions brings error msg saying "unable to remove one or more extensions..." 

Log shows current state: The first few error was there originally;

Download the React DevTools for a better development experience: https://fb.me/react-devtools
/utils/DeprecationWarning.js:88 PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (/preferences/PreferencesManager.js:323:28)
    at Object.eval (/utils/Resizer.js:557:24)

These few following are new (and the end ones were there before)

/utils/DeprecationWarning.js:88 Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:123:32)
    at Object.<anonymous> (file:///C:/Users/Nick/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:384:29)
/utils/DeprecationWarning.js:88 Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:123:32)
    at Object.<anonymous> (file:///C:/Users/Nick/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:385:29)
/utils/DeprecationWarning.js:88 Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:123:32)
    at Object.<anonymous> (file:///C:/Users/Nick/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:386:26)
/utils/DeprecationWarning.js:88 Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:123:32)
    at Object.<anonymous> (file:///C:/Users/Nick/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:387:28)
/utils/DeprecationWarning.js:88 Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:123:32)
    at Object.<anonymous> (file:///C:/Users/Nick/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:388:26)
/utils/DeprecationWarning.js:88 Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:123:32)
    at Object.<anonymous> (file:///C:/Users/Nick/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:389:29)
/utils/DeprecationWarning.js:88 Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:123:32)
    at Object.<anonymous> (file:///C:/Users/Nick/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:390:28)
/utils/DeprecationWarning.js:88 Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:123:32)
    at Object.<anonymous> (file:///C:/Users/Nick/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:391:26)


_And these seem the same as when I first tried to install._

/command/KeyBindingManager.js:578 Fail to nomalize Cmd-Shift-]
/command/KeyBindingManager.js:578 Fail to nomalize Cmd-Shift-[
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - start
/filesystem/FileSystem.js:904 Failed to watch root:  C:/Users/Nick/Desktop/html/ Max connection attempts reached
/project/ProjectManager.js:748 Error watching project root:  C:/Users/Nick/Desktop/html/ Max connection attempts reached

Hope this report helps those who are looking into this - happy to try anything people suggest and report back.

Thanks
nicksoph

**Comment by nicksoph** [comment]
Replacement of node version - worked for me on a - 32bit win10 machine

see comment - https://github.com/adobe/brackets/issues/12918#issuecomment-261337603

ficristo commented on 17 Nov
@K-Thompson is your platform a 32 bit one?
If so could you try to replace the node executable you find in C:\Program Files\Brackets with the one you can dowload from http://nodejs.org/dist/v6.3.1/win-x86/?

**Comment by bizanniusz** [comment]
change your node.exe from installer brackets download here https://nodejs.org/en/download/ and choice Windows Binary (.exe), and restar bracket! than its work! +1:

**Comment by doige** [comment]
So. 
We put the node.exe file which is in brackets 1.7 into 1.8 and now we can update and install extensions. This can't be the solution, but it works. Weird. 

I hope it will be fixed in 1.9.

**Comment by ficristo** [comment]
This should be fixed in 1.9.
If you want to give a try with there is a prerelease at https://github.com/adobe/brackets/releases

**Comment by hrvojegolcic** [comment]
Try modifying the extension to use `"view/WorkspaceManager"` instead of `"view/PanelManager"`. I had problem installing the most of the extensions too.
https://github.com/adobe/brackets/issues/11960#issuecomment-374403225

**Comment by Ganesh619** [comment]
> Replacement of node version - worked for me on a - 32bit win10 machine
> 
> see comment - [#12918 (comment)](https://github.com/adobe/brackets/issues/12918#issuecomment-261337603)
> 
> ficristo commented on 17 Nov
> @K-Thompson is your platform a 32 bit one?
> If so could you try to replace the node executable you find in C:\Program Files\Brackets with the one you can dowload from http://nodejs.org/dist/v6.3.1/win-x86/?

 its not working
