### ISSUE TITLE
Feature request: Comments in PHP 

### ISSUE THREAD

**Issue by TilakMaddy** [adobe/brackets#12985]
When you select lines of text and hit `#` , I want each line to be preceded with `#` and become a comment

**Comment by haslam22** [comment]
![4wmkl7l03l](https://cloud.githubusercontent.com/assets/9113599/21279313/8a6c6d4a-c3d7-11e6-9662-efa78cad0165.gif)


You can select multiple lines to comment by holding CTRL + clicking the start of each line. Is this what you're looking for?

**Comment by redmunds** [comment]
@TilakMaddy As @haslam22 said, use `Ctrl+/` to toggle the `lineComment` defined for the language.

If you look in languages.json, the definition of `php` looks like this:

```
    "php": {
        "name": "PHP",
        "mode": "php",
        "fileExtensions": ["php", "php3", "php4", "php5", "phtm", "phtml", "ctp"],
        "blockComment": ["/*", "*/"],
        "lineComment": ["//", "#"]
    },
```

Since `//` is the first `lineComment` then that one is used. Change the order to use `#` instead:

```
        "lineComment": ["#", "//"]
```

Then use _Debug > Open User Key Map_ to change the shortcut (although you'll have to use a modifier key something like `Ctrl+#`).

**Comment by TilakMaddy** [comment]
Thanks , I got it.
