### ISSUE TITLE
Help with 'IF' Commands!

### ISSUE THREAD

**Issue by NikkiRaeGamer** [adobe/brackets#12998]
str.toLowerCase(trustbarry)
    
    if (trustbarry = "Yes" | "sure" | "ok" | "trust barry" | "yes trust barry" | "I will trust barry" | "Trust barry please" | "mhmm" | "ok I trust barry" | "ok, I trust Barry" | "please trust barry" | "I trust barry" | "I trust barry" | "You trust barry"){
        
        alert("You: Deciding to trust Barry, you say, 'Ok, I trust you, Barry'");
        alert("Barry: 'Thanks Richard, I need at least someone on my side.");

    } else if (trustbarry = "no" | "no way" | "no way jose" | "nope" | "I do not trust barry" | "I don't trust barry" | "Don't trust him" | "do not trust barry" | "I do not want to trust barry" | "I don't want to trust barry" | "I don't" | "I do not"){
        alert("You: 'No, Barry, I don't think I can trust you.");
        alert("Barry: 'Richard, You're making a mistake, please, just trust me.");
        alert("You: You think hard, and even though you're really confused and scared, you say 'Fine, but no mistakes, I can't take any chances'");
        alert("Barry: 'You have my word' Barry said.");
         }

-------------------------------------------------------------------------------------

That above was my part of code for and 'if' command followed by an 'else if' command. Now testing out my brackets DOES work, but, when I say 'YES' or 'OK' on the var 'trustbarry' command, the system does not continue to where it's suppose to go. For example, "Do you trust Barry? Yes or no?" if I write 'YES' it does nothing :(

Can anyone help me with this? Thanks.

**Comment by haslam22** [comment]
`trustbarry = "Yes` actually means you're setting the `trustBarry` variable to "Yes", whereas you probably wanted `trustBarry === "Yes"` to compare the values.

Also when doing a long if statement like that, you need add `trustBarry === "value"` before every condition, like so:

`if(trustBarry === "Yes" || trustBarry === "sure" || trustBarry === "trust barry" || ...)`

Also use `||` instead of `|`.

And finally, you want to make sure that you're comparing against lowercase strings only, e.g. `"I will trust barry"` in your if statement will never be true because you set the string to lowercase, and you're comparing against a string with an uppercase character.

**Comment by ficristo** [comment]
Not a Brackets issue, closing.
