### ISSUE TITLE
Brackets 1.8 does not support es6 in the UI portion of extensions in Linux

### ISSUE THREAD

**Issue by catdad** [adobe/brackets#13096]
### Description

Since Brackets updated to Node 6, I have been using it in my extension, which I primarily develop on Windows. On Windows, I can wrote es6 both in the main UI portion of an extension, as well as in a Node domain, and both work just fine. I loaded up the extension on Brackets 1.8 (the latest installed last night) on Ubuntu 16, and the UI portion of the extension gets syntax errors for all es6 code. The Node domain portion correctly executes using es6. When I remove es6 from the Ui portion of the extension, it works fine. Isn't all JavaScript code supposed to be running against Node 6 in Brackets 1.8?

### Steps to Reproduce

1. Load an extension with es6 in the main part of the extension on Windows -- for example, use template strings using backticks.
2. Load same extension on Linux (I used Ubuntu 16).

**Expected behavior:**

Both Windows and Linux should execute that extension correctly.

**Actual behavior:**

Windows executes the extension correctly, but Linux received syntax errors.

### Versions

Windows 10 using Brackets 1.8 (latest as of 2/11/17).
Ubuntu 16.04 using Brackets 1.8 (latest as of 2/11/17).

**Comment by petetnt** [comment]
Hi @catdad,

this is sadly a long running issue of the Linux version going out of date due to the difficulty of integrating/keeping up with CEF releases on the Linux version. The Brackets-Electron version that we now usually recommend to install over the CEF Linux version has vastly better support for ES2015 features AFAIK, but I understand that this might not be a solution for an extension.

Note to self: Might be worth adding that issue to the Linux Guide too: https://github.com/adobe/brackets/wiki/Brackets-Linux-Guide.

**Comment by catdad** [comment]
Thanks for the info, that's good to know. I already updated my code, so that's not a big deal. But it is good to know that I will need to test against Brackets-Electron, since that is officially recommended in the docs.

**Comment by ficristo** [comment]
Now Linux build should be in par with Windows and macOS.
See https://github.com/adobe/brackets-shell/pull/619
