### ISSUE TITLE
Navigating between large, code folded files causes performance problems

### ISSUE THREAD

**Issue by lkcampbell** [adobe/brackets#13282]
**OS:** MacS 10.12.3 Sierra and Windows 10

**Brackets Version:** Release 1.9 build 1.9.0-17312 (release 189f6d39a) 

**Repro  Steps:**
1. Make sure `code-folding.enabled` preference is set to `true`.
1. Make sure `code-folding.saveFoldStates` preference is set to `true`.
1. Set `code-folding.maxFoldLevel` preference to a high number like `100`. Collapse all should really be collapsing *all* folds.
1. Create two decent sized xml test files. I'm using [this file](https://raw.githubusercontent.com/jmandel/sample_ccdas/master/HL7%20Samples/CCD.sample.xml) for both of my test files.
1. Open both files so they are in the `Working Files` section of the Project Sidebar.
1. `Collapse All` both files so there is plenty of fold state data.
1. Navigate back and forth between the two files continuously, showing one, then the other, in the editor.

**Observed Results:**
After three or four loops of navigating to each file, the time it takes for the contents of each file to show up in the editor will get longer and longer, roughly doubling in time for each loop. Eventually, the delay is so long the files can no longer be navigated in a reasonable amount of time.

**Expected Results:**
The time to navigate to each test file should be about the same regardless of how many time you loop between them.

**Workaround:**
Make sure `code-folding.saveFoldStates` preference is set to `false`. You will need PR https://github.com/adobe/brackets/pull/13269 before you can use this workaround.

**Other Notes:**
The problem occurs with all extensions disabled.

Since this problem goes away when fold states are turned off, and the time seems to roughly be doubling each time, maybe new fold states are being appended to old fold states instead of replacing them. Feels like there might be some redundant, duplicate data being saved somewhere, just a theory, haven't tested it.

**Comment by lkcampbell** [comment]
Pinging @thehogfather, wanted to make sure you saw this issue, Patrick.

**Comment by thehogfather** [comment]
@lkcampbell got it 👍 .

**Comment by lkcampbell** [comment]
@thehogfather let me know if you need help. I am curious if my theory is correct. Either way, let me know.

**Comment by thehogfather** [comment]
@lkcampbell your theory is in the right direction - but we could nail it down better. The problem is not actually with the routine for saving fold states. The issue occurs when we attempt to restore the saved fold states for the editor gaining focus.

Here is a quick overview of what I have found so far.
When the active editor changes, the fold states for the editor losing focus are saved while the fold states for the editor gaining focus are restored. Saving is not costly. Restoration however involves several calls to codeMirror functions for rendering fold marks on the gutter and creating folded marks in the document. We need to perform this operation at least once - although there is no need to restore the folds for a document already in the working set. 

The reason why setting `saveFoldStates: false` gets rid of the problem is because there is nothing to restore when the `saveFoldStates` is set to false. Hence the `restoreLineFold` function has an early exit.
_Mind you I am still not sure why calling the function to fold some code and generate the html markup becomes less and less performant. We might need to do some further profiling._

So a quick experiment to address this issue is to prevent the redundant call to restore line folds for files already in the working set. I am currently not aware of any API available in brackets to check if a file is in the working set, (but for now a workaround is to check if the editor object has `editor._codeMirror._lineFolds`). Do you know of an existing API that doe the same thing?

Here are a couple of charts from a profiling experiment
### Buggy
<img width="1316" alt="screenshot_09_04_2017__21_59" src="https://cloud.githubusercontent.com/assets/1283787/24841104/cc5e577c-1d73-11e7-9bbf-24751c360bf9.png">

### Patched
Ignore the idle time at the start of this profile. It is clear that the first two calls to switching between the files are still slow - and we can try to figure out how to improve that still. But subsequent calls are close to instantaneous.
<img width="1325" alt="screenshot_09_04_2017__22_10" src="https://cloud.githubusercontent.com/assets/1283787/24841137/6af41d72-1d74-11e7-8182-21a1f7a118bd.png">

**Comment by lkcampbell** [comment]
@thehogfather that's an *impressive* improvement with your patch. I will probably have more time to look into this Friday and this weekend. I will see if I can find an answer to your Brackets API question then as well.

**Comment by lkcampbell** [comment]
@thehogfather, I think MainViewManager.findInWorkingSet() is the Brackets API you want to use.

**Comment by thehogfather** [comment]
oh awesome I'll have a play with that.

**Comment by thehogfather** [comment]
@lkcampbell After tinkering with `MainViewManager.findInAllWorkingSets` I decided it was not quite right for this use case.  For instance when Brackets is opened, it may already contain a list of files in the working set from a prior session (even before any user interaction). Hence presence in the working set does not necessarily mean the fold gutters and states have been initialised/restored for a given editor. See a16d58e1003fb433afd395cf8db2f52affb62f00 for details of my fix if you would like to test.

**Comment by lkcampbell** [comment]
@thehogfather, okay, it *looked* like the right API from the documentation. There has to be a way to  tell if a file is in the current working set somewhere, but let's not let it block getting this bug fixed. I will take a look at your fix soon, thanks.

**Comment by thehogfather** [comment]
@lkcampbell the initial fault in framing the problem is mine as I assumed that the presence of a file in the working set implies that the Editor fold gutters would have been initialised. This is not always the case. Specifically when Brackets is closed and re-launched, files are added to the working set based on settings saved from the previous session. I believe this is largely because code folding is still loaded as an extension and not initialised as part of the `Editor` constructor. I think this is fine since initialising code folding could be expensive and it is best loaded on demand.

So to be clear, the API you suggested does exactly what it says on the tin - unfortunately that functionality is not what we need to solve the problem here.

**Comment by lkcampbell** [comment]
@thehogfather, your change already got merged before I had a chance to look at it :). I will test it later today and update this issue appropriately.

**Comment by lkcampbell** [comment]
Closing as fixed.
