### ISSUE TITLE
Using x-tags with Brackets

### ISSUE THREAD

**Issue by brendonmm** [adobe/brackets#13405]
Hello,

I'm testing the use of x-tags for an extension in Brackets that shows the clock inside the editor. To do this, I followed the Extensions examples and applied the basic x-clock code directly to the Extension I made. On Windows it works normally, but in Linux doesn't work.

![image](https://cloud.githubusercontent.com/assets/2398403/26615152/40209cd4-459b-11e7-96b4-ed0e819230ea.png)

elementaryOS:

![image](https://cloud.githubusercontent.com/assets/2398403/26638094/a73b321a-45f7-11e7-83dc-10207c46e78b.png)

Windows:

![image](https://cloud.githubusercontent.com/assets/2398403/26638054/9069559e-45f7-11e7-952e-04757e5164c0.png)

I was wondering if it would be a Brackets issue, or x-tags, or even OS, so I'm posting here first.`Thank you.

This is the error that shows in Brackets:

![image](https://cloud.githubusercontent.com/assets/2398403/26615145/308097ac-459b-11e7-8a0b-673c024f57a4.png)

elementaryOS 0.4.1 Loki and/or Ubuntu 16.04
Release 1.9 experimental build 1.9.0-17312

**Comment by ficristo** [comment]
If doesn't work on Linux, it is possibly related to the version of shell used there.
Brackets is still running Chrome 29 on Linux.

**Comment by brendonmm** [comment]
Got it. What I found weird is that x-tags' site tells that it supports all versions of Chrome.

![image](https://cloud.githubusercontent.com/assets/2398403/26655605/d99088fc-4631-11e7-8df1-3450655b9e06.png)


I noticed that the shell used was an old one, although I opened DevTools inside my current Chrome, which has the updated version, not 29.

Is there any version of Brackets in Linux with newer shell? I can install via npm if necessary. Or a forecast for an update on Linux?

**Comment by ficristo** [comment]
You could use https://github.com/zaggino/brackets-electron on Linux, which use electron as the shell instead of cef.

According to http://caniuse.com/#search=registerElement, registerElement is supported since Chrome 33.
But custom element were supported since Chrome 27 but behind a flag.
So maybe you can try to launch Brackets with that flag.
I think something like `brackets --enable-experimental-web-platform-features`
(I don't know if that will work, nor if the flag is correct...)

Probably @saurabh95 know the situation regarding the shell on Linux.

**Comment by ficristo** [comment]
This should have been fixed by https://github.com/adobe/brackets-shell/pull/619
Now Linux build run on Chrome 51.
