### ISSUE TITLE
Doesn't want to open java code

### ISSUE THREAD

**Issue by AlexStefanov2** [adobe/brackets#13478]
OS - windows 7 home premium
Brackets version - 1.8.0.0

When I right click a .jar file and then select "Open with brackets" it gives the error message "Brackets currently only supports UTF-8 encoded text files.

I know that brackets is just glorified notepad, but it would be awesome if I could open and edit java code inside brackets (since I mainly use it as my "IDE for everything")

**Comment by petetnt** [comment]
Hi @AlexStefanov2,

the error message isn't due to Java-files exactly, but with the character encoding of the files. The files are most likely encoded in UTF-8 but with BOM or as some other ASCII format, which Brackets didn't handle up until https://github.com/adobe/brackets/pull/13412 and https://github.com/adobe/brackets/pull/13477. 

While those should land in 1.10, meanwhile you could open the files in another editor (for example Notepad++ on Windows), convert the files to plain UTF-8 and open them again in Brackets.

**Comment by petetnt** [comment]
Closing as fixed, please do reopen if issue persists with Brackets 1.10-1.11
