### ISSUE TITLE
How to hide empty sidebar

### ISSUE THREAD

**Issue by ezequias** [adobe/brackets#13576]
Hi

I am getting a white sidebar and can no longer hide it. I didn't figure it out what is causing the problem.

See the imagem and understand.
![bracketswhitesidebar](https://user-images.githubusercontent.com/539561/28570169-3c2c35ae-7113-11e7-8af9-44a1c7c48a2f.jpg)

**Comment by ficristo** [comment]
Most likely an extension problem.
Could you try to run "Debug \ Reload Without Extensions" to confirm ?

**Comment by ezequias** [comment]
@ficristo the problem does not occurs without extension.  There is a way to find out which is the one is causing the issue?

**Comment by ezequias** [comment]
I found the extension. It was Custom Work the one I loved the most 😢. Thanks your help.

**Comment by petetnt** [comment]
Hi @ezequias,

there's another issue at the Custom Work repo https://github.com/DH3ALEJANDRO/custom-work-for-brackets/issues/88 that states it's caused by incompatibility with another extension `Brackets Outline List` and has some [workarounds](https://github.com/DH3ALEJANDRO/custom-work-for-brackets/issues/88#issuecomment-310137923)

> The error is caused by the following extension: "Brackets Outline List"
> possible solutions:
>
> Remove "Brackets Outline List"
> Uncheck the "moveToolbarToSidebar" preference from "Custom Work"

If you are using Brackets Outline List too, you could try other conflicting extensions and report them to @DH3ALEJANDRO 👍

**Comment by ezequias** [comment]
Thank you so much @petetnt It worked!
