### ISSUE TITLE
Unable to install brackets on Debian 64/32 Bit

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#13666]
### Description

Unable to install brackets on Debian 64/32 Bit

### Steps to Reproduce

1. Install brackets on debian 64/32 bit using
sudo dpkg -i "path to brackets .deb file"
2. It gives following error as shown in screenshot below:
![image](https://user-images.githubusercontent.com/25339865/30114739-4b6ea80e-9336-11e7-907b-ed71a54f3d81.png)

**Expected behavior:** Debian should install without giving error
**Actual behavior:** Unable to install brackets on Debian 64/32 Bit

### Versions

Linux Debian 64/32 Bit
Brackets Release 1.11 build 1.11.0-17507

**Comment by slipttees** [comment]
try apt-get -f install

**Comment by saurabh95** [comment]
This is probably not a legitimate error, this is quite common with Linux apps, since it is not feasible to package every dependency in the installer as it would make it quite heavy.
@slipttees is right, Linux identifies that there are some apps installed with some dependencies not met, then using `sudo apt-get -f install -y` will install all such dependencies.
