### ISSUE TITLE
[Remote File] The live preview does not open for the unsaved file.

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14307]
### Description
The live preview does not open for the unsaved file.

### Steps to Reproduce
1. Launch brackets 1.13.
2. Press ctrl+shift+O for win and cmd+shift+O for mac.
3. Quick open modal bar will open.
4. Enter a network url that supports http or https. Example: https://www.google.com
5. The code for the page is displayed in brackets and file is visible in working files in file tree.
6. Click on live preview button. 

**Expected behavior:** The live preview should open for the unsaved file as well.

**Actual behavior:** The live preview does not open for the unsaved file.

### Versions
Win 10 64 Bit
Mac 10.12
Release 1.13 build 1.13.0-17668

**Comment by sobisht** [comment]
@ayushrathi15 This behaviour is expected. Since, the remote file is not present in the project, live preview won't be displayed for it.

https://github.com/adobe/brackets/wiki/Troubleshooting#files-should-be-in-current-project has reference of this behaviour.

If you save the code as an html file in the project folder, then the live preview will be displayed.

**Comment by ayushrathi15** [comment]
This is As Designed.
Hence closing the issue.
