### ISSUE TITLE
Cannot turn off tag auto closing

### ISSUE THREAD

**Issue by zonamoroza** [adobe/brackets#14575]
Hi, 

I have searched the forum for the solution, however, nothing helped, I still cannot turn off tag auto closing function. How can I do this? 

Thank you!

Darya

**Comment by zonamoroza** [comment]
@MerryPanda what would you prefer it optional as well?

**Comment by MerryPanda** [comment]
> 
> 
> @MerryPanda what would you prefer it optional as well?

i would prefer that we had GUI (not just pref file) to manage such things ^_^

**Comment by navch** [comment]
Hi @MerryPanda I guess you could find an extension for that. Actually, brackets try to avoid dialogues or popup that's why we have everything in-line like error messages. No feature uses extra dialogues like find, quick open, go to line etc.

@zonamoroza You can find some solution [here ](https://github.com/adobe/brackets/issues/14156#issuecomment-437636590)

Closing this issue, Feel free to reopen if you still have any issues.
