### ISSUE TITLE
I am an beginner in coding and this question is not about resolving an issue but a question I have. 

### ISSUE THREAD

**Issue by A-mirSaleh** [adobe/brackets#14856]
I have been coding in brackets code editor version 1.14.0 on Macbook OS X and encountered the '.DS_Store' file in my file. The question is, how can this file be a hinder, or better phrasing my question is .ds store file bad for your computer and why? Should care about it.
Are there other ways that it might cause problems like slowing down computers or so. I did not exactly find info about this file when I looked it up but there is of course a lot of how to remove it posts, blogs, etc. 
Thank you in advance to anyone who answers my question.

**Comment by xypd** [comment]
@A-mirSaleh, these are normal invisible file the Mac makes for storing information about files on your hard drive. For example what label you added to a picture in the finder etc. You don't need to get rid of these on a Mac. On other OS such as linux or windows you can. They are also automatically generated.

You're seeing them in brackets because the program needs to show all files. Since you don't understand the working of Mac OS, I would suggest not trying to remove them or change the OS. At least until you get more experience.

Here a few helpful links.

https://en.wikipedia.org/wiki/.DS_Store

http://osxdaily.com/2009/12/31/what-is-a-ds_store-file/
