### ISSUE TITLE
I want Brackets off my computer NOW!!! DO NOT DOWNLOAD THIS TERRIBLE SOFTWARE

### ISSUE THREAD

**Issue by Liam-Nestor** [adobe/brackets#15031]
I can not delete, update, uninstall Brackets on my computer Adobe is a joke.

I want this fixed and will never use adobe software again and advise anyone else to do the same

**Comment by xypd** [comment]
A bit dramatic.

However, this doesn't doesn't seem like a very useful post.

* You want this software off you computer
What operating system are you on?
What have you tried?
Do you have this issue with any other software?

* Telling people to not download some software because of specific issue can be useful.
Your not sharing what you issue was.
How can you help other that could share you problem?
What is making the software in your words "Terrible"?

I hope you solve your issue or can provide enough help that someone can help. I've been using brackets for many year without major issues (lot of little issues, but no show stoppers). I'm currently using it on MacOS.

Have a look at some of these issue submissions and how they are formatted.
- #14966
- #14992
- #15013

Cheers

**Comment by DingBEN** [comment]
Liam drama queen,
Please be thorough in your clear explanation, backed with all the system(your) information and all the versions, and the error/issue you face, etc... so that I may make a correct assessment as to why I would avoid **'BRACKETS'** as my new Editor env.   #15032 is my currently posted issue.
