### ISSUE TITLE
rethink live development server provider interface

### ISSUE THREAD

**Issue by joelrbrandt** [adobe/brackets#3007]
(cc @redmunds @njx @gruehle)

We have a preliminary interface for live development servers, but we probably want to improve (or maybe elimate!) it going forward. I'm creating this bug so we can track possible improvements.

One thing that I've already found a use case for is: We could modify (and probably rename) the ```readyToServe``` call to take in a filename and return a promise that resolves to a URL (or rejects if the server doesn't want to handle the file). Doing this, an extension developer could implement an extension that, e.g., figures out what path to serve a Ruby on Rails file at. These files don't have a 1:1 mapping to urls, but an intelligent extension could do the mapping.

@alltom wants this.

**Comment by mathetos** [comment]
Just pulled out Brackets again today to work on a WordPress theme and encountered the same issue that @DigiSquidinc mentioned over a YEAR ago. Is Brackets dying a slow death, or is just this one (fundamental) issue that affects all CMS's (not just WordPress) being ignored for some reason?

**Comment by DigiSquidinc** [comment]
It seems to me that getting Brackets live preview to work with CMS systems is a low priority for the devs (heck, it's literally marked *low priority* here). So I'm going to guess that their focus is primarily static site development. I personally haven't built a static site in years, so I've pretty much stopped using the app altogether - though I do still check in on it from time to time. :-)

**Comment by peterflynn** [comment]
@mathetos The Brackets community has never been bigger or more vibrant.  But if you look at the [Brackets feature backlog](https://trello.com/b/LCDud1Nd/brackets), there are over 400 feature ideas listed.  Even in a year, we can't build them all.  (Lots has been going on -- check out the [history board](https://trello.com/b/RHzQZKTv/brackets-history), everything left of the Sprint 35 column was done last year! -- but there's lots more to do, so it's a matter of prioritizing).

In this case the relevant backlog items are:

* [RESEARCH: Make Live Development Work For Router-Based Technologies](https://trello.com/c/uKewlref/708-research-make-live-development-work-for-router-based-technologies)
* [Live HTML updating with user web server (Node, Rails, etc.) & static HTML](https://trello.com/c/U9iOhk4J/1129-live-html-updating-with-user-web-server-node-rails-etc-static-html)
* [Live Development with dynamic server side pages](https://trello.com/c/09jhB0hV/573-live-development-with-server-side-pages)

This is all complex work, so it can't happen overnight.  But one thing people can do to help raise the priority is to upvote those backlog stories!  Currently none of those stories even rank in the top 50 by votes.

Since this issue is actually redundant with what's on the backlog, I'm going to close this.  There's lots of great discussion above though, so I'll link back here or try to summarize the discussion in the backlog cards.

**Comment by peterflynn** [comment]
Also see [Live Preview: using a local server is confusing](https://trello.com/c/7OaIE6lV/1301-live-preview-using-a-local-server-is-confusing) on the backlog. If we're smart about how we address that, it could help with these router/CMS situations too.

**Comment by DigiSquidinc** [comment]
> Currently none of those stories even rank in the top 50 by votes.

Which really surprises me because I haven't come across anyone still developing static sites professionally in ages, nor have I had any requests from clients for this type of work. Obviously that's anecdotal, but I assumed that working with dynamic sites/frameworks was more or less the norm these days.

Even still, I respect that my workflow doesn't necessarily *everyone's* workflow and clearly those of us requesting this feature are in the minority.

**Comment by peterflynn** [comment]
@DigiSquidinc Nonetheless, I do agree it's an important workflow that Brackets should care about supporting.  More upvotes will help.  Also, Live Preview is currently undergoing some flux due to the new "Multi-Browser Live Preview" functionality that's in progress.  Once the dust settles from that, I'd hope this is the thing we'll tackle next within the Live Preview area.

In addition to upvotes of course, since this is open source people are also welcome to take the initiative and put up a pull request or write up an architecture/spec proposal!  That goes a _long_ way.  Starting a discussion about the implementation and behavior, e.g. on [brackets-dev](http://groups.google.com/group/brackets-dev), is a good first step for anyone interested in that.

**Comment by DigiSquidinc** [comment]
Thanks for the feedback @peterflynn. If Live Preview supported server-based technologies, Brackets would easily become my primary editor. But, without it, I simply can't use it. So I do hope that the value of this workflow gains some attention. 

As it stands, there are virtually no apps or IDEs on the market geared towards interface designers / developers working with server-based technologies. So we're forced to use hacky third-party workarounds or manually reload our browsers each time we need to see an update.

If I could replace this clunky workflow with something like Brackets, I'd be thrilled.

**Comment by theboss388** [comment]
Only just stumbled upon Brackets and, whilst it seems like a great editor, I have to echo what others are saying really.

I work solely with WordPress and any editor I use must be compatible.

Live preview is something that would be greatly welcomed, but the current implementation of it in Brackets just doesn't work well with WordPress at all. Ideally, it shouldn't change the file in live preview to the one you are editing, this just doesn't help at all. It should stay as showing the site itself in the live preview screen and just allow edits to be added automatically.

**Comment by baberuth22** [comment]
This issue certainly shouldn't be closed.  I still can't live preview my Wordpress sites.

A simple solution would be allowing the user to specify a file -> url array.

Eg.   template-wall.php  =>  /wall

Easy right?

**Comment by Taariqq** [comment]
Hi guys!

Are you guys using an alternative that is better? Is vscode doing the job? Did someone address this issue before Brackets was (perhaps) abandoned?

I am new to the world of web dev and just starting out with wordpress. I was thrilled with the live preview in Brackets and that was the main reason keeping me from switching to vscode.

Does anyone have a solution that will help me stay with Brackets?
