### ISSUE TITLE
Highligth code issue

### ISSUE THREAD

**Issue by Dragod** [adobe/brackets#3741]
I was adding some css like:

div > .yourclass {...}

but that is not highlight on the previewer

if you write:

ul > li {...} that work.

Is that a bug?

**Comment by ficristo** [comment]
I created a `test.css` file and added 
```css
div > .yourclass {}
ul > li {}
```
which is highlighted correctly.
It's not really clear to me what you meant with previewer, but since this had no answer and to me works fine, I close this.
FYI there is this issue which is about to differentiate tags and custom classes: https://github.com/adobe/brackets/issues/12558
