### ISSUE TITLE
Editor and BOM  (byte order mark)

### ISSUE THREAD

**Issue by ghost** [adobe/brackets#3898]
Editor show BOM  (byte order mark) with red dot at begin of file.

UPD: Windows 7, Brackets Sprint 24.

**Comment by Tigt** [comment]
Some minification programs automatically use a BOM instead of a typical encoding declaration to squeeze out a few more bytes; in particular, Sass's production mode will output the BOM instead of `@charset "utf-8";` when it detects non-ASCII characters inside the final file. I would love it if Brackets did BOM handling in a robust, discoverable way; the consequences can be dire for things like Ruby.

**Comment by Download** [comment]
I'd like to offer my two cents on this issue, as Unicode encoding has become something of an issue that is dear to me. 

First, I'd like to address a couple of remarks made here:

@busykai 
> Couple of assumptions:
>
> BOM for UTF-8 does not make any sense (it's just 1 byte). A BOM indicating UTF-8 does exist though.

@njx 
> since the BOM is not important, the most we should do is preserve it, but it would be fine to just strip it. 

Please do reconsider your opinion on this. The Byte Order Mark really is very badly named, as all emphasis is laid on Byte Order, which (as you say) does not make sense for UTF-8, but in fact this marker serves two purposes. The byte-order thing is just half of the story. 

> Q: What is a BOM?
> A: A byte order mark (BOM) consists of the character code U+FEFF at the beginning of a data stream, where it can be used as a signature defining the byte order **and encoding form**, primarily of unmarked plaintext files.
<sub><sup>([Unicode FAQ](http://unicode.org/faq/utf_bom.html), emphasis mine)<sub><sup>

The second purpose of the BOM is as a signature mark, to identify the content as Unicode encoded. In this world filled with legacy encodings, this second function is actually much more important than the first one. Why? Because in practical reality today, UTF-8 is the only encoding that is actually in widespread use. But one of the biggest advantages of UTF-8 encoding, backwards compatibility with ASCII, is also it's Achilles' heel; it's near impossible for editors and tools opening UTF-8 encoded text to tell the difference between ASCII, ANSI, ISO-8859-x and UTF-8. We need to either ask the user, make assumptions (just assume UTF-8 for example) or make some [guesstimate](https://blogs.msdn.microsoft.com/oldnewthing/20040324-00/?p=40093) based on file content... Sometimes with [very weird results](http://weblogs.asp.net/cumpsd/81098).

Many applications allow the user to specify the encoding. Some even offer explicit control over the BOM character.... But really, most user's don't have the knowledge to make informed decisions about these issues. Brackets targets programmers but even most programmers don't understand the intricacies of text encodings. As such, Brackets has an important function. The standards it chooses to set and the defaults it chooses will have a big impact on the community, because most programmers will simply use these defaults without ever thinking about them. As such I urge you to study this matter in great detail and take the time (and give this issue enough priority) such that you can pick those defaults that will leave us with as little problems as possible in 10 years time when thousands or even millions of files will have been created using these defaults.

**Please write out the Unicode BOM as the first character of every new file by default**

The BOM is specified in the Unicode standard. It's the lowest possible level where this could have been standardized (as opposed to in some OS or filesystem, or even at the application level). That is **fantastic** because it means we can get out of the encoding hell. Any application that claims to support Unicode **must** understand the BOM. So technically you can write out the BOM in front of every UTF-8 file you save and it should never cause any problems. If it does, the application reading the file is violating the Unicode standard.

I just really badly want all those milions of files that are (hopefully :) going to be created with Brackets to have BOMs in front of them so text editors and any other software processing text files won't have to *guess* about the encoding it's in because it will *know* from the BOM that it is indeed UTF-8 encoded Unicode text and nothing else.

Now in practical reality there is still software around that does not fully support Unicode and has trouble with the BOM... This very issue being one example. For those scenarios it's good to have the option to suppress it. The suggestion from @busykai for a small GUI in the status bar sounds fantastic. Just please, please, please set the BOM to *enabled* for new files. It will save us so much pain in the long run.

**Comment by Download** [comment]
In the meantime I read the user story on the backlog that was referenced in this issue and it is very interesting to read the discussion there in the context of the Unicode BOM. It specifically mentions that it is very hard to detect the encoding of a file.

If you embrace the BOM, this makes the world so much easier! Just:

* read the first bytes of the file to detect the BOM
* If it's there, great! You will *know* the encoding and you are done.
* If it's not there life becomes more complex. You have to somehow decide on the encoding to use
** Assume UTF-8 and scan the file for byte sequences that *violate UTF-8*. Have a look at this Wikipedia page: [UTF-8#Codepage layout](https://en.wikipedia.org/wiki/UTF-8#Codepage_layout). The red cells are invalid byte sequences. This allows us to rule out UTF-8 in some scenario's.
** If no illegal UTF-8 bytes were found, just open the file as UTF-8. This allows you to stay backward-compatible with older versions of Brackets
** If illegal UTF-8 characters were found, open up a 'Specify encoding' dialog that lets the user pick from the list of whichever encodings you choose to support and then just open the file in that format.

Starting to write out the BOM on saving UTF-8 files now will mean you will be able to get rid of the scanning for illegal UTF-8 sequences earlier or maybe even just skip it at all, because you will be able to reliably detect which encoding was used to save the file. And with you, all other tools that support Unicode. Long live the BOM!  :)
