### ISSUE TITLE
Ability to turn off code hinting

### ISSUE THREAD

**Issue by 1c7** [adobe/brackets#4716]
My computer performance is not very good....
when i use brackets 28.. edit javascript code are slow..
  
example:   input "al"(alert) or "fun"(function).. 
software will stop.. wait about 300~500 Millisecond. 
then pop out auto complete list...
this is Annoying...
how to close auto complete Feature?
Thanks!

**Comment by peterflynn** [comment]
We've had the ability to turn off code hints for quite some time now.  The secondary issue in this bug is poor performance of JS code hints, but we have a bunch of items in Trello about improving JS code hints ([such as this one](https://trello.com/c/cNVSkHPV/1235-epic-javascript-code-hints-cleanup)).  Any objections to closing this?  (CC @dangoor, assignee)

**Comment by dangoor** [comment]
:+1:

**Comment by ifexdebest** [comment]
How can i turn off code hinting?

**Comment by redmunds** [comment]
@ifexdebest 

> How can i turn off auto tag closing?

See info about the `closeTags` preference in [How to Use Brackets doc](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences).
