### ISSUE TITLE
Wish for Feature: Use brackets to easier develop apps in node-webkit

### ISSUE THREAD

**Issue by ljgww** [adobe/brackets#6657]
I love live preview in the browser while developing front end.

Since engine shall be fairly same (do not know details) I hope it is possible to do the same development facilities with node-webkit (in the same fashion as with chrome). This would accelerate developing of desktop applications in HTML.

ref: https://github.com/rogerwang/node-webkit

**Comment by hdf** [comment]
+1
nw.js is the future, and currently there are no IDE -s for it. I think brackets would be a great fit.
What stands in the way of using nw.js as live preview instead of chrome?

**Comment by nethip** [comment]
@jasonsanjose I recall you talking about a possible implementation of node-webkit based approach. Could you fill in more details here?

**Comment by peterflynn** [comment]
@nethip I believe that was research about running Brackets itself on top of node-webkit (instead of brackets-shell as today).  The request here is about pointing Live Preview at node-webkit (instead of the _Chrome browser_ as today).

With Multi-Browser Live Preview, this should already work.  For classic Live Preview, which probably isn't going away in the near future, it's more complex -- should probably be part of the [Live Development w/ Custom Chrome Install](https://trello.com/c/MYaUdJOR/508-live-development-w-custom-chrome-install-e-g-canary-portable-chrome-dartium) story.  I'll add a note there and then close this.
