### ISSUE TITLE
Installing extension from filesystem

### ISSUE THREAD

**Issue by ghost** [adobe/brackets#7472]
Hi, 

am currently working on an extension i can't open source right away.
In order to make it available on a private network, i need to find a place where it can be downloaded anonymously which is not easy.

An easy solution for that problem would be a button "Install Extension from File System", then i could download the extension and install it later on.

**Comment by DenisVuyka** [comment]
What would be extremely valuable is having multiple paths for extensions to collect during startup. Continuously copying files between git-initialized folder and "user" folder is very annoying and inconvenient. 
Here's a scenario I personally miss a lot: 
_as a developer I want to point Brackets to "my extension" project folder (git-initialized) during extension development (in addition to "user" folder). Once my extension is finished I can simply push it to remote repository without additional efforts involved_
This could probably satisfy @ghost request as well. Thanks in advance.

**Comment by peterflynn** [comment]
Closing since the feature as originally requested above was added to Brackets last summer.

@DenisVuyka For the use case you're describing, use the `src/extensions/dev` folder within the Brackets source code tree -- that's exactly what it's designed for.  See [this note under 'How to Write Extensions'](https://github.com/adobe/brackets/wiki/How-to-Write-Extensions#creating-an-extension) for more info.
