### ISSUE TITLE
Need to Document: brackets opens an additional copy of chrome for live preview

### ISSUE THREAD

**Issue by evbvd** [adobe/brackets#9773]
**Original Subject:** brackets opens an additional copy of chrome for live preview

if I have chrome open already when I launch brackets, it opens a second chrome application rather than using my already open chrome. not just a new window, but another copy of chrome entirely. I only have one copy of chrome on my hard drive, so this is a mystery to me.

it sometimes decides to open the new chrome in another "space", which is really really irritating. defeats the purpose of live preview.

have I set something up wrong, or is this a bug that can be addressed? osx 10.8.5; chrome 38.0.2125.111; brackets Release 0.44 experimental build 0.44.0-14876 (release 6d2d33d80)

**Comment by sammarcus** [comment]
Could this be documented somewhere? it was driving me mad, I was convinced this was a problem with my machine. Where is this second instance pulling prefs from, and saving history, etc? I'm surprised it can coexist at the same time so peacefully without any chaos. I had no idea this functionality was intentional! Thanks for your help, @redmunds!

**Comment by redmunds** [comment]
> Could this be documented somewhere?

I will re-open this issue for updating the documentation in [How to Use Brackets](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#live-preview) to include info about using a different profile.

> Where is this second instance pulling prefs from, and saving history, etc?

This [section](https://github.com/adobe/brackets/wiki/Troubleshooting#clear-live-preview-profilecache) in Troubleshooting Guide describes where Brackets saves the profile info.

**Note:** since this issue was opened, a new [Experimental Live Preview](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#experimental-live-preview) has been added to Brackets that uses your default browser with no special profile that you may prefer.

**Comment by sammarcus** [comment]
Awesome, thanks so much @redmunds! Very, very helpful!

**Comment by rroshan1** [comment]
Updated the Documentation [How to Use Brackets](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#live-preview) with the info- Brackets opens an additional copy of chrome for live preview.
Closing the issue.

**Comment by sammarcus** [comment]
Thank you, @rroshan1! :+1:
