### ISSUE TITLE
Adobe Extract needs internet!

### ISSUE THREAD

**Issue by abdelouahabb** [adobe/brackets#9793]
This is a great tool, but i have to be all the time online? cant we use it offline? (asks for an Adobe ID)

**Comment by eraustud** [comment]
The proper approach to this is "we're looking at online use cases."
The only reason to put the extraction app online is so that you can update it rapidly during preview development or guard proprietary parser code. If this goes to Release without a local parser, it would eliminate most use cases for this software in commercial applications.

No marketing department or creative services organization is going to want to upload unreleased, unfinished collateral for a third party's reading pleasure.

**Comment by peterflynn** [comment]
@eraustud See above: "We’re looking at the offline use cases" is exactly the statement that was given.

The Creative Cloud privacy agreement is pretty strict, so files you upload are certainly _not_ "for a third party's reading pleasure" -- [see Section 3](http://www.adobe.com/legal/general-terms.html), in particular: "We will not access, view, or listen to any of your content, except as reasonably necessary to perform the Services."   Lots of creative professionals use online services, including Creative Cloud, Dropbox, etc. that are entrusted with their private content.  I get that not everyone in the world is comfortable with that yet, but certainly plenty of teams are.

**Comment by eraustud** [comment]
Thank you for replying. You may want to read the post once again, more 
carefully.
I suggested that Ryan's statement should have read "*online* use cases" 
because the statement does read "offline use cases" and reflects a 
backward thought process. The default parsing mode should be offline so 
that the application can be used in a secure environment and during 
travel, not online so that it can be DRM-locked as Adobe is wont to do.

Requiring file upload to a remote parser violates security and KISS 
principles in addition to reducing application reliability and 
performance (it's not going to be faster to upload a multi-MB file, 
remote-parse and return results unless the client computer is so old 
that it can't even run Brackets).

Remote parsing during Preview makes perfect sense if the parser itself 
is being actively developed, as it allows application updates to be 
immediately effective for the entire user base. However, the stable, 
final Release version would be better served by having the parser run 
locally.

Last, given that Adobe had over 150M customer account records leaked 
less than 18 months ago, their entire attitude toward security as a 
business is untrustworthy, regardless of any privacy agreements. A 
company of Adobe's size that prioritizes information integrity and 
account security would have systems and people in place that notice and 
stop an attack in a shorter time frame than is required to pull 
150,000,000 records from even a high-speed database.

**Comment by artlantis** [comment]
Same for me. Right now I am working behind the proxy which is controlling by hardware firewall. Therefore, the Brackets does not connect to Adobe Cloud service. Brackets always throw an error message like:

```javascript
 [node-error 8:30:08 AM] /ims/check/v1/token?client_id=bracketsextract1&scope=AdobeID%2Copenid%2Ccreative_cloud%2Ccreative_sdk&locale=en-US&redirect_uri=brackets-auth%3A%2F%2Fredirectims.html%23from_ims%3Dtrue%26old_hash%3D%26api%3Dcheck%252Ftoken&callback=jQuery213016175519302487373_1426832986543&e4b-target-domain=https%3A%2F%2Fadobeid-na1.services.adobe.com&_=1426832986544 - Error from EventEmitter3.emit(): Error: connect ETIMEDOUTErrorNotification.js:125 window.console.errormain.js:418 console.errorNodeDebugUtils.js:114 handleLogEvent/utils/EventDispatcher.js:222 trigger/utils/EventDispatcher.js:260 triggerWithArray/utils/NodeConnection.js:479 NodeConnection._receive
ErrorNotification.js:125 A network error has occurred. Are you connected to the internet?

**Comment by nethip** [comment]
@jasonsanjose Any thoughts on how to resolve these firewall issues?

**Comment by jasonsanjose** [comment]
You might check with @dangoor since he's familiar with the proxy handling that was implemented for the extension registry.

**Comment by dangoor** [comment]
If I recall correctly, the proxy value can be passed in when making requests in Node and that's all we did with that proxy flag.

**Comment by onlymaj** [comment]
Also in some countries like mine i see this :
> 403 Forbidden
> Request forbidden by administrative rules.

its better to use local offline method . it's not reasonable to upload about 200MB files on the cloud to use this system btw.

**Comment by ProbadorGit** [comment]
Totally agree. Extract was one of the main reasons I installed Brackets (to improve my workflow performance) and then I was massively disappointed to see I need to sign in and upload my PSD files. I will install Brackets again when/if the feature is included as online. Hopefully soon!

**Comment by Cactusx09** [comment]
+1

**Comment by jdavies322** [comment]
> But we’re interested in hearing how an offline use case would be helpful

Offline is not just helpful but essential as far as my firm is concerned. I tried the tool out today with the demo PSD, and it is neat, but there is no way in heck I would ever consider uploading proprietary client artwork to the cloud. No matter what Adobe's Privacy-Agreement-of-the-minute says.

I get that Extract is beta and having it online assists in development, but I can't actually use it for real-world projects under an online use paradigm.

I find Adobe's push to get creatives to upload production files to CreativeCloud disturbing. Finished portfolio pieces that you wanna get #social with? Maybe. Client production artwork? No way!

**Comment by ryanstewart** [comment]
We announced last week that we're going to be [discontinuing support for Extract for Brackets on June 28th](http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/). And there aren't an plans to support an offline version in Brackets. The Dreamweaver team (who is currently working on integrating Brackets as their code surface) may be looking into offline support but I'm not sure where it is on their roadmap.

Because of the announcement I'm going to go ahead and close this issue. But if you have any questions, feel free to email me: ryan@adobe.com or post them here and I'll try to follow up.
