### ISSUE TITLE
Fonts of titlebar menu items aren't rendering properly in Ubuntu.

### ISSUE THREAD

**Issue by nmabhinandan** [adobe/brackets#9828]
The menu items of the title bar menu aren't rendering properly in Ubuntu OS. They look kinda dull and thin.
![screenshot from 2014-11-06 17 38 12](https://cloud.githubusercontent.com/assets/1548848/4935591/e9e479f4-65ae-11e4-85fe-a969ca565199.png)

It looks better by adding `font-weight: 400` to the anchor links of the menu. (The 'File' and 'Edit' items are modified using developer tools) 
![screenshot from 2014-11-06 17 42 58](https://cloud.githubusercontent.com/assets/1548848/4935625/3da030ec-65af-11e4-9216-3cc6f56461ce.png)

**Comment by nmabhinandan** [comment]
:+1:  Nice fix.

**Comment by FriendOfFatBeagle** [comment]
I installed Brackets on Linux Mint 17.1
It is a variant of Ubuntu 14.xx.
I installed Mark's extension.  Nothing happens, even after restarting app..
 Suggestions?

**Comment by busykai** [comment]
@FriendOfFatBeagle, firstly, you do not need to install extension any longer as it is fixed in the core. The way it has been fix is illustrated by the screenshots in [this comment](https://github.com/adobe/brackets/pull/9829#issuecomment-64059347). Are you seeing something different than "after" screenshot?

@Mark-Simulacrum, by the way, if your extension does not do anything extra than your PR #9829, may be it is worth removing the extension from the registry.

**Comment by Mark-Simulacrum** [comment]
@busykai Removed the extension from the registry, it didn't do anything more than the PR did.

**Comment by FriendOfFatBeagle** [comment]
>>  "firstly, you do not need to install extension any longer as it is fixed in the core. The way it has been fix is illustrated by the screenshots in this comment. Are you seeing something different than "after" screenshot?"

 @busykai:  If this is fixed in the core, why do I still have microscopic size fonts for UI menu and left pane?
I did not see any difference between the before and after screenshots you mentioned.

I could zoom in and out for the text inside the editor, but UI menu and left pane text is like 5 points.
Really really small.


Here is a screen shot from my display:

![screenshot from 2015-05-24 17 59 12](https://cloud.githubusercontent.com/assets/4752711/7790263/ab532104-023e-11e5-8ae0-f7019ef6fbb6.png)

**Comment by busykai** [comment]
@FriendOfFatBeagle, thanks for the screenshot and the explanation. What you're describing is different from the original issue. As far as I can tell, everything's working as designed: you can resize the editor font, but you cannot resize/scale fonts in other elements. The original issue was that the menu fonts were rendering too thin. I guess what you're saying is:

1. the fonts used in the menu and in the file tree are too small;
2. there's no feature to make them bigger.

I need a Linux machine to actually install and try. From the screenshot you're providing, it's not clear how much scaled is the editor as opposed to its normal size. Comparing it to the actual size of fonts on my Mac, they seem about the same size. It's not to say it could be a problematic for some. The motivation for this design choice, if I'm not mistaken, was that it's what's within the editor that actually matters, menus and file tree should not stand on its way (i.e. occupy too much space or have bright colors).

Did you try to use the OS accessibility features to accomplish the task? For example, I can use "Zoom" on Mac to magnify the window if I cannot see the text.

**Comment by FriendOfFatBeagle** [comment]
>>>  I guess what you're saying is:
    the fonts used in the menu and in the file tree are too small;
    there's no feature to make them bigger.
@busykai:
Yes, that is correct conclusion.

I have yet to find a good magnifier for Linux Mint.
The GUI font is tiny, like 5 point or less on my 17.5" display laptop.
If you open up OpenOffice or libreOffice, compare 5 or 6 points vs 12 points font and see the difference, so you get an idea of the problem..... 
 
>> Comparing it to the actual size of fonts on my Mac, they seem about the same size. 
When I ran Brackets on Win 7 for the same dual boot laptop, the GUI fonts were of proper size.
But I want to work in Linux, and want to detach myself from Windows, as much as possible.
So this problem is specific to Linux Mint or may be also other Debian variants.

**Comment by busykai** [comment]
@FriendOfFatBeagle, thanks. I see the magnitude of the problem now. Could you please file a separate issue and provide a screenshot with 1) a default Brackets theme (dark or light) and 2) without any editor magnification? It would probably be helpful if you included part of the desktop (anything that includes text rendered by the system) so that whoever will be evaluating the issue later will be able to judge how tiny the fonts are (in comparison).

**Comment by busykai** [comment]
@Mark-Simulacrum, thank you! It will help to avoid confusion.

**Comment by FriendOfFatBeagle** [comment]
@busykai:
Here is the filed problem report:
https://github.com/adobe/brackets/issues/11161

Let me know if it needs more clarifications ....
Thanks.

**Comment by FriendOfFatBeagle** [comment]
@busykai or anyone:
I did not know why someone closed by problem report here:
https://github.com/adobe/brackets/issues/11161

Since I am using Linux, my problem should be common amongst Linux users.
Surely there is a solution already.
I  tried Atom editor, and it has similar problem since it is a web/browser technology based editor.

It was solved using this plugin:    https://atom.io/packages/hidpi
It has an explanation on why UI font is not working in Linux like it should in Mac.
Excerpts:
Atom HiDPI / Retina
Atom Hidpi scales Atom's interface based on the current monitor's resolution. Currently on Linux Atom does not scale based on DPI, so this package is necessary to make Atom readable on monitors with high resolutions / DPIs. This package should not be necessary for OSX because it automatically scales. I have not tested Atom on Windows so I do not know how it behaves.

I did not know enough of Brackets to do any good at the moment.
Please advice.

**Comment by MarcelGerber** [comment]
@FriendOfFatBeagle Could you just quickly try this:
1. Go to `Debug > Show developer tools`
2. Switch over to the `Console` tab
3. Enter `brackets.app.setZoomLevel(2)` and hit return

(You'll probably get the best results by uninstalling your other appearance-changing extensions previously)

Is this workable for you?

**Comment by MarcelGerber** [comment]
Oh, I see now. As you're on Linux, you probably don't have that command yet. Too bad.

**Comment by FriendOfFatBeagle** [comment]
Yes, correct.
In Dev Tools Console:
brackets.app.setZoomLevel(2)
TypeError: Object #<Object> has no method 'setZoomLevel'
